import type {
  PluginInput,
  PluginOutput,
  Operation,
} from '@adhd/apigen-core-client';
import { envelopeKey, sanitizeIdentifier } from '@adhd/apigen-engine-naming';
import { HTTP_STATUS } from '@adhd/apigen-base-errors';
import type { ProjectionConfig } from '@adhd/apigen-engine-naming';
import { resolveRoute } from './route-projection';

// ---------------------------------------------------------------------------
// §5 — route + verb derivation (BUG-APIGEN-OPENAPI-ROUTE-PATH-MISMATCH-001):
// both are now derived via `project()` from `@adhd/apigen-engine-naming` — see
// `./route-projection.ts` — so generated routes.ts is byte-identical to what
// `@adhd/apigen-plugin-openapi` advertises for the same operation. No longer
// duplicated per plugin.
// ---------------------------------------------------------------------------

/**
 * `generate()`'s input.
 *
 * DEBT-APIGEN-PLUGIN-MCP-GENERATE-OPERATIONS-001 (RESOLVED): `PluginInput`
 * (`@adhd/apigen-core-client`) now carries an optional `operations?:
 * Operation[]` field directly, threaded through by `entrypoint/apigen-cli`'s
 * `orchestrateGenerate()` the same way `orchestrateRun()` threads
 * `RunInput.operations` (BUG-APIGEN-024) — so this is populated in the CLI's
 * actual wiring today, giving fully byte-identical-to-openapi codegen output.
 * `resolveRoute()` falls back to a synthesized single-segment Operation only
 * when a caller builds a bare `PluginInput` with no `operations` at all (e.g.
 * a unit test).
 */
type GenerateInput = PluginInput & { operations?: Operation[] };

// ---------------------------------------------------------------------------
// §9.1 helpers — envelope field metadata carried on a schema entry
// ---------------------------------------------------------------------------

/**
 * Returns a map of envelope field names → their `x-<pluginId>-<field>` header keys.
 *
 * Reads `x-apigen-envelope` from the schema (a Record<field, pluginId>).
 * Falls back to treating each top-level non-`data` property as a builtin `adhd` field.
 */
function envelopeHeaders(
  schema: Record<string, unknown>
): Record<string, string> {
  const inputProps =
    ((schema['input'] as Record<string, unknown> | undefined)?.[
      'properties'
    ] as Record<string, unknown> | undefined) ?? {};
  const meta = schema['x-apigen-envelope'] as
    | Record<string, string>
    | undefined;
  const result: Record<string, string> = {};
  for (const field of Object.keys(inputProps)) {
    if (field === 'data') continue;
    const pluginId = meta?.[field] ?? 'adhd';
    result[field] = envelopeKey(pluginId, field);
  }
  return result;
}

export function generate(input: GenerateInput): PluginOutput {
  const port = (input.options['port'] as number) ?? 3000;
  const routePrefix = (input.options['routePrefix'] as string) ?? '';
  const projection =
    (input.options['projection'] as ProjectionConfig | undefined) ?? {};

  const lines: string[] = [
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
    `import Fastify from 'fastify'`,
    `import { dispatch, buildFnTable, coerceQueryParams } from '@adhd/apigen-engine-runtime'`,
  ];
  for (const pkg of input.packages) {
    const varName = sanitizeIdentifier(pkg.id);
    lines.push(`import * as ${varName}_ns from '${pkg.importPath}'`);
    lines.push(
      `const ${varName}_fns = buildFnTable(${varName}_ns as Record<string, unknown>)`
    );
  }
  lines.push(``);

  // Build the schemas map — includes x-apigen-safe + x-apigen-envelope hints.
  lines.push(
    `const schemas: Record<string, unknown> = ${JSON.stringify(
      Object.fromEntries(
        input.packages.flatMap((p) =>
          Object.entries(p.schemas).map(([fn, s]) => [
            `${p.id}:${fn}`,
            { schema: s, pkgId: p.id },
          ])
        )
      ),
      null,
      2
    )}`
  );
  lines.push(``);
  lines.push(`const app = Fastify()`);
  lines.push(``);

  for (const pkg of input.packages) {
    const varName = sanitizeIdentifier(pkg.id);
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      const { route, verb } = resolveRoute(
        pkg.id,
        fnName,
        fnSchema as Record<string, unknown>,
        input.operations,
        routePrefix,
        projection
      );
      const headerMap = envelopeHeaders(fnSchema as Record<string, unknown>);
      const headerEntries = Object.entries(headerMap);

      if (verb === 'GET') {
        // safe op: domain args from query string, envelope from request headers
        lines.push(`app.get('${route}', async (req) => {`);
        // FEAT-APIGEN-022: query strings are always strings — coerce to the
        // domain schema's declared number/integer/boolean types before
        // dispatch (never touches POST/body — see coerce-query.ts).
        lines.push(
          `  const query = coerceQueryParams(req.query as Record<string, unknown>, schemas['${pkg.id}:${fnName}']['schema'] as any)`
        );
        if (headerEntries.length > 0) {
          const envParts = headerEntries
            .map(
              ([field, hdr]) =>
                `'${field}': (req.headers as Record<string, unknown>)['${hdr}']`
            )
            .join(', ');
          lines.push(
            `  const envelope: Record<string, unknown> = { ${envParts} }`
          );
        } else {
          lines.push(`  const envelope: Record<string, unknown> = {}`);
        }
        lines.push(
          `  return dispatch(${varName}_fns as any, undefined, schemas['${pkg.id}:${fnName}']['schema'] as any, '${fnName}', envelope, query as any)`
        );
        lines.push(`})`);
      } else {
        // unsafe op: domain args from body.data, envelope from request headers
        lines.push(`app.post('${route}', async (req) => {`);
        lines.push(
          `  const { data = {} } = req.body as Record<string, unknown>`
        );
        if (headerEntries.length > 0) {
          const envParts = headerEntries
            .map(
              ([field, hdr]) =>
                `'${field}': (req.headers as Record<string, unknown>)['${hdr}']`
            )
            .join(', ');
          lines.push(
            `  const envelope: Record<string, unknown> = { ${envParts} }`
          );
        } else {
          lines.push(`  const envelope: Record<string, unknown> = {}`);
        }
        lines.push(
          `  return dispatch(${varName}_fns as any, undefined, schemas['${pkg.id}:${fnName}']['schema'] as any, '${fnName}', envelope, data as any)`
        );
        lines.push(`})`);
      }
    }
  }

  lines.push(``);
  lines.push(`app.listen({ port: ${port} })`);

  return { files: [{ path: 'routes.ts', content: lines.join('\n') }] };
}

// Re-export error status map for use in route error handlers (§9).
export { HTTP_STATUS };
