import type { PluginInput, PluginOutput } from '@adhd/apigen-core'
import { envelopeKey } from '@adhd/apigen-naming'
import { HTTP_STATUS } from '@adhd/apigen-errors'
import type { ProjectionConfig } from '@adhd/apigen-naming'

// ---------------------------------------------------------------------------
// §9.1 helpers — envelope field metadata carried on a schema entry
// ---------------------------------------------------------------------------

/**
 * Returns the effective HTTP verb for a function's schema.
 *
 * Verb derives from the `x-apigen-safe` hint per SPEC §5:
 *   safe → GET (query-string params, cacheable)
 *   unsafe (default) → POST
 *
 * Per-operation overrides via `projection.http.verb.<fnId>` take precedence.
 */
function httpVerb(
  fnId: string,
  schema: Record<string, unknown>,
  config: ProjectionConfig,
): 'GET' | 'POST' {
  const override = config.http?.verb?.[fnId]
  if (override === 'GET' || override === 'POST') return override
  return (schema['x-apigen-safe'] as boolean | undefined) ? 'GET' : 'POST'
}

/**
 * Returns a map of envelope field names → their `x-<pluginId>-<field>` header keys.
 *
 * Reads `x-apigen-envelope` from the schema (a Record<field, pluginId>).
 * Falls back to treating each top-level non-`data` property as a builtin `adhd` field.
 */
function envelopeHeaders(schema: Record<string, unknown>): Record<string, string> {
  const inputProps = (
    (schema['input'] as Record<string, unknown> | undefined)?.['properties'] as
      | Record<string, unknown>
      | undefined
  ) ?? {}
  const meta = schema['x-apigen-envelope'] as Record<string, string> | undefined
  const result: Record<string, string> = {}
  for (const field of Object.keys(inputProps)) {
    if (field === 'data') continue
    const pluginId = meta?.[field] ?? 'adhd'
    result[field] = envelopeKey(pluginId, field)
  }
  return result
}

export function generate(input: PluginInput): PluginOutput {
  const port = (input.options['port'] as number) ?? 3000
  const routePrefix = (input.options['routePrefix'] as string) ?? ''
  const projection = (input.options['projection'] as ProjectionConfig | undefined) ?? {}

  const lines: string[] = [
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
    `import Fastify from 'fastify'`,
    `import { dispatch, buildFnTable } from '@adhd/apigen-runtime'`,
  ]
  for (const pkg of input.packages) {
    lines.push(`import * as ${pkg.id}_ns from '${pkg.importPath}'`)
    lines.push(`const ${pkg.id}_fns = buildFnTable(${pkg.id}_ns as Record<string, unknown>)`)
  }
  lines.push(``)

  // Build the schemas map — includes x-apigen-safe + x-apigen-envelope hints.
  lines.push(
    `const schemas: Record<string, unknown> = ${JSON.stringify(
      Object.fromEntries(
        input.packages.flatMap((p) =>
          Object.entries(p.schemas).map(([fn, s]) => [
            `${p.id}:${fn}`,
            { schema: s, pkgId: p.id },
          ]),
        ),
      ),
      null,
      2,
    )}`,
  )
  lines.push(``)
  lines.push(`const app = Fastify()`)
  lines.push(``)

  for (const pkg of input.packages) {
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      const route = `${routePrefix}/${pkg.id}/${fnName}`
      const verb = httpVerb(`${pkg.id}:${fnName}`, fnSchema as Record<string, unknown>, projection)
      const headerMap = envelopeHeaders(fnSchema as Record<string, unknown>)
      const headerEntries = Object.entries(headerMap)

      if (verb === 'GET') {
        // safe op: domain args from query string, envelope from request headers
        lines.push(`app.get('${route}', async (req) => {`)
        lines.push(`  const query = req.query as Record<string, unknown>`)
        if (headerEntries.length > 0) {
          const envParts = headerEntries
            .map(([field, hdr]) => `'${field}': (req.headers as Record<string, unknown>)['${hdr}']`)
            .join(', ')
          lines.push(`  const envelope: Record<string, unknown> = { ${envParts} }`)
        } else {
          lines.push(`  const envelope: Record<string, unknown> = {}`)
        }
        lines.push(
          `  return dispatch(${pkg.id}_fns as any, undefined, schemas['${pkg.id}:${fnName}']['schema'] as any, '${fnName}', envelope, query as any)`,
        )
        lines.push(`})`)
      } else {
        // unsafe op: domain args from body.data, envelope from request headers
        lines.push(`app.post('${route}', async (req) => {`)
        lines.push(`  const { data = {} } = req.body as Record<string, unknown>`)
        if (headerEntries.length > 0) {
          const envParts = headerEntries
            .map(([field, hdr]) => `'${field}': (req.headers as Record<string, unknown>)['${hdr}']`)
            .join(', ')
          lines.push(`  const envelope: Record<string, unknown> = { ${envParts} }`)
        } else {
          lines.push(`  const envelope: Record<string, unknown> = {}`)
        }
        lines.push(
          `  return dispatch(${pkg.id}_fns as any, undefined, schemas['${pkg.id}:${fnName}']['schema'] as any, '${fnName}', envelope, data as any)`,
        )
        lines.push(`})`)
      }
    }
  }

  lines.push(``)
  lines.push(`app.listen({ port: ${port} })`)

  return { files: [{ path: 'routes.ts', content: lines.join('\n') }] }
}

// Re-export error status map for use in route error handlers (§9).
export { HTTP_STATUS }
