import type { PluginInput, PluginOutput } from '@adhd/apigen-core'

export function generate(input: PluginInput): PluginOutput {
  const port = (input.options['port'] as number) ?? 3000
  const routePrefix = (input.options['routePrefix'] as string) ?? ''

  const lines: string[] = [
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
    `import Fastify from 'fastify'`,
    `import { dispatch, buildFnTable } from '@adhd/apigen-runtime'`,
  ]
  for (const pkg of input.packages) {
    lines.push(`import * as ${pkg.id}_ns from '${pkg.importPath}'`)
    lines.push(`const ${pkg.id}_fns = buildFnTable(${pkg.id}_ns as Record<string, unknown>)`)
  }
  lines.push(``)
  lines.push(
    `const schemas: Record<string, unknown> = ${JSON.stringify(
      Object.fromEntries(
        input.packages.flatMap((p) =>
          Object.entries(p.schemas).map(([fn, s]) => [
            `${p.id}:${fn}`,
            { schema: s, pkgId: p.id },
          ]),
        ),
      ),
      null,
      2,
    )}`,
  )
  lines.push(``)
  lines.push(`const app = Fastify()`)
  lines.push(``)
  for (const pkg of input.packages) {
    for (const fnName of Object.keys(pkg.schemas)) {
      const route = `${routePrefix}/${pkg.id}/${fnName}`
      lines.push(`app.post('${route}', async (req) => {`)
      lines.push(`  const { data = {}, ...envelope } = req.body as Record<string, unknown>`)
      lines.push(
        `  return dispatch(${pkg.id}_fns as any, undefined, schemas['${pkg.id}:${fnName}']['schema'] as any, '${fnName}', envelope, data as any)`,
      )
      lines.push(`})`)
    }
  }
  lines.push(``)
  lines.push(`app.listen({ port: ${port} })`)

  return { files: [{ path: 'routes.ts', content: lines.join('\n') }] }
}
