/**
 * gate.spec.ts — unit tests for the conformance gate logic.
 *
 * Tests (with teeth):
 *   1. A conformant host set passes the full matrix.
 *   2. A host whose supportedIds is missing a canonical id FAILS (⊇ enforcement).
 *   3. A vector whose negativeControl mutation does NOT turn the host RED is
 *      itself flagged (proves the checks aren't vacuous).
 *   4. The discovery mechanism finds both the TS and Python hosts.
 *   5. A manifest-only host with empty supportedIds is non-conformant.
 */

import { describe, it, expect, beforeEach } from 'vitest'
import * as path from 'node:path'
import * as os from 'node:os'
import * as fs from 'node:fs'

import {
  CANONICAL_IDS,
  checkSupportedIds,
  constructSeedTs,
  checkInvariantTs,
  runTsMatrix,
  getTsHostManifest,
  getPythonHostManifest,
  discoverManifestHosts,
  discoverHosts,
  runConformanceMatrix,
} from '../lib/gate'
import type { HostManifest, VectorRunResult } from '../lib/gate'

import {
  logicalTypeVectors,
} from '../lib/vectors'
import type { LogicalTypeVector } from '../lib/vectors'

import {
  dateTimeCodec,
  int64Codec,
  decimalCodec,
  byteCodec,
  uuidCodec,
  numberSpecialCodec,
  LOGICAL_TYPE_VERSION,
} from '@adhd/apigen-logical'
import type { LogicalTypeCodec, LogicalTypeId } from '@adhd/apigen-logical'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const WORKSPACE_ROOT = path.resolve(__dirname, '..', '..', '..', '..', '..')

/** The canonical well-known codec map used by the TS matrix runner. */
const TS_CODEC_MAP = new Map<LogicalTypeId, LogicalTypeCodec>([
  ['date-time', dateTimeCodec],
  ['int64', int64Codec],
  ['decimal', decimalCodec],
  ['byte', byteCodec],
  ['uuid', uuidCodec],
  ['number-special', numberSpecialCodec],
])

/** Build a fully-conformant HostManifest for the TS host. */
function conformantTsManifest(): HostManifest {
  return {
    host: 'ts',
    logicalTypeVersion: LOGICAL_TYPE_VERSION,
    supportedIds: [...CANONICAL_IDS],
    deps: {},
  }
}

/** Build a HostManifest with one canonical id missing. */
function manifestMissingId(missingId: LogicalTypeId): HostManifest {
  return {
    host: 'ts-missing',
    logicalTypeVersion: LOGICAL_TYPE_VERSION,
    supportedIds: CANONICAL_IDS.filter((id) => id !== missingId),
    deps: {},
  }
}

/** Build a HostManifest with empty supportedIds (as generated by `nx generate apigen-nx:host`). */
function emptyManifest(host: string): HostManifest {
  return {
    host,
    logicalTypeVersion: LOGICAL_TYPE_VERSION,
    supportedIds: [],
    deps: {},
  }
}

// ---------------------------------------------------------------------------
// 1. checkSupportedIds — ⊇ enforcement
// ---------------------------------------------------------------------------

describe('checkSupportedIds — supportedIds ⊇ canonical', () => {
  it('[conformant] a manifest covering all canonical ids passes (empty errors)', () => {
    const errors = checkSupportedIds(conformantTsManifest())
    expect(errors).toHaveLength(0)
  })

  it('[missing-one] a manifest missing "date-time" produces an error for that id', () => {
    const errors = checkSupportedIds(manifestMissingId('date-time'))
    expect(errors.length).toBeGreaterThan(0)
    expect(errors.some((e) => e.includes('date-time'))).toBe(true)
  })

  it('[missing-one] a manifest missing "int64" produces an error for that id', () => {
    const errors = checkSupportedIds(manifestMissingId('int64'))
    expect(errors.some((e) => e.includes('int64'))).toBe(true)
  })

  it('[missing-all] empty supportedIds produces errors for every canonical id', () => {
    const errors = checkSupportedIds(emptyManifest('new-host'))
    expect(errors.length).toBe(CANONICAL_IDS.length)
    for (const id of CANONICAL_IDS) {
      expect(errors.some((e) => e.includes(id))).toBe(true)
    }
  })

  it('[NEGATIVE teeth] a missing id is actually detected — removing the check makes it pass vacuously', () => {
    // Prove the test would catch a regression: if we supply the FULL id set,
    // the function MUST return 0 errors (not accidentally error on a known id).
    const full = checkSupportedIds(conformantTsManifest())
    expect(full).toHaveLength(0)

    // Now strip one id — must get exactly one error
    const stripped = checkSupportedIds(manifestMissingId('byte'))
    expect(stripped.some((e) => e.includes('byte'))).toBe(true)
  })
})

// ---------------------------------------------------------------------------
// 2. TS matrix — conformant host passes
// ---------------------------------------------------------------------------

describe('runTsMatrix — TS host (conformant)', () => {
  it('[encode] all vectors encode seed to canonical wire', () => {
    const results = runTsMatrix(logicalTypeVectors, TS_CODEC_MAP)
    const encodeResults = results.filter((r) => r.phase === 'encode')
    const failures = encodeResults.filter((r) => !r.pass)
    expect(
      failures,
      `encode failures:\n${failures.map((f) => `  ${f.vectorId}: ${f.error}`).join('\n')}`,
    ).toHaveLength(0)
  })

  it('[invariants] all vectors decode wire and satisfy invariants', () => {
    const results = runTsMatrix(logicalTypeVectors, TS_CODEC_MAP)
    const invResults = results.filter((r) => r.phase === 'invariant')
    const failures = invResults.filter((r) => !r.pass)
    expect(
      failures,
      `invariant failures:\n${failures.map((f) => `  ${f.vectorId}: ${f.error}`).join('\n')}`,
    ).toHaveLength(0)
  })

  it('[negative-controls] all negative controls turn the vector RED', () => {
    const results = runTsMatrix(logicalTypeVectors, TS_CODEC_MAP)
    const ncResults = results.filter((r) => r.phase === 'negative-control')
    const failures = ncResults.filter((r) => !r.pass)
    expect(
      failures,
      `vacuous negative controls:\n${failures.map((f) => `  ${f.vectorId}: ${f.error}`).join('\n')}`,
    ).toHaveLength(0)
  })

  it('[full-pass] all phases pass for all vectors', () => {
    const results = runTsMatrix(logicalTypeVectors, TS_CODEC_MAP)
    const failures = results.filter((r) => !r.pass)
    expect(
      failures,
      `full matrix failures:\n${failures.map((f) => `  ${f.vectorId} (${f.phase}): ${f.error}`).join('\n')}`,
    ).toHaveLength(0)
  })
})

// ---------------------------------------------------------------------------
// 3. TS matrix — host missing a canonical id FAILS
// ---------------------------------------------------------------------------

describe('runTsMatrix — host with missing supportedId', () => {
  it('[TEETH-1] missing "date-time" id in supportedIds triggers a failure', () => {
    // The checkSupportedIds function is the gate — verify it fails.
    const stripped = manifestMissingId('date-time')
    const errors = checkSupportedIds(stripped)
    expect(errors.length).toBeGreaterThan(0)
    expect(errors.some((e) => e.includes('date-time'))).toBe(true)
  })

  it('[TEETH-2] a codec map missing the date-time codec cannot run the vector', () => {
    // Remove one codec from the map to simulate a non-conformant host.
    const partialMap = new Map(TS_CODEC_MAP)
    partialMap.delete('date-time')
    const results = runTsMatrix(logicalTypeVectors, partialMap)
    // The date-time vector must have an encode failure.
    const dtFail = results.find(
      (r) => r.vectorId === 'logical.date-time.roundtrip' && r.phase === 'encode' && !r.pass,
    )
    expect(dtFail, 'expected a failure for missing date-time codec').toBeDefined()
    expect(dtFail!.error).toMatch(/no codec registered/)
  })

  it('[TEETH-3] removing all codecs causes every vector to fail', () => {
    const emptyMap = new Map<LogicalTypeId, LogicalTypeCodec>()
    const results = runTsMatrix(logicalTypeVectors, emptyMap)
    const encodeFailures = results.filter((r) => r.phase === 'encode' && !r.pass)
    expect(encodeFailures.length).toBe(logicalTypeVectors.length)
  })
})

// ---------------------------------------------------------------------------
// 4. Negative-control non-vacuity: the checks actually fail when the codec is broken
// ---------------------------------------------------------------------------

describe('runTsMatrix — negative-control non-vacuity', () => {
  it('[nc-teeth] the negative control for date-time turns red (non-UTC offset wire)', () => {
    const results = runTsMatrix(logicalTypeVectors, TS_CODEC_MAP)
    const ncResult = results.find(
      (r) => r.vectorId === 'logical.date-time.roundtrip' && r.phase === 'negative-control',
    )
    expect(ncResult).toBeDefined()
    // Must be pass=true meaning "the check DID turn red" (the gate verified the mutation is non-conformant)
    expect(ncResult!.pass).toBe(true)
  })

  it('[nc-teeth] the negative control for int64 turns red (numeric wire instead of string)', () => {
    const results = runTsMatrix(logicalTypeVectors, TS_CODEC_MAP)
    const ncResult = results.find(
      (r) => r.vectorId === 'logical.int64.roundtrip' && r.phase === 'negative-control',
    )
    expect(ncResult).toBeDefined()
    expect(ncResult!.pass).toBe(true)
  })

  it('[nc-teeth] the negative control for byte turns red (URL-safe base64 wire)', () => {
    const results = runTsMatrix(logicalTypeVectors, TS_CODEC_MAP)
    const ncResult = results.find(
      (r) => r.vectorId === 'logical.byte.roundtrip' && r.phase === 'negative-control',
    )
    expect(ncResult).toBeDefined()
    expect(ncResult!.pass).toBe(true)
  })

  it('[nc-teeth] the negative control for uuid turns red (uppercase wire)', () => {
    const results = runTsMatrix(logicalTypeVectors, TS_CODEC_MAP)
    const ncResult = results.find(
      (r) => r.vectorId === 'logical.uuid.roundtrip' && r.phase === 'negative-control',
    )
    expect(ncResult).toBeDefined()
    expect(ncResult!.pass).toBe(true)
  })

  it('[nc-teeth] the negative control for NaN turns red (null wire)', () => {
    const results = runTsMatrix(logicalTypeVectors, TS_CODEC_MAP)
    const ncResult = results.find(
      (r) => r.vectorId === 'logical.number-special.nan' && r.phase === 'negative-control',
    )
    expect(ncResult).toBeDefined()
    expect(ncResult!.pass).toBe(true)
  })

  it('[nc-NEGATIVE-vacuous] a vacuous negative control (same wire) is detected', () => {
    // Craft a vector where negativeControl.to === wire — must be flagged as vacuous.
    // We simulate this by running a vector with a mutated negativeControl that maps back to canonical wire.
    // The gate should produce pass=false for that negative-control check.
    const dtVector = logicalTypeVectors.find((v) => v.logicalType === 'date-time')!
    // A mutation that does NOT change the wire (same value = vacuous)
    const vacuousVector: LogicalTypeVector = {
      ...dtVector,
      id: 'test.vacuous-nc',
      negativeControl: {
        mutate: 'wire',
        // Same wire as canonical = vacuous (decoding it still satisfies invariant /epochMs
        // for the exact same timestamp — nothing changes)
        to: dtVector.wire,
      },
    }
    const results = runTsMatrix([vacuousVector], TS_CODEC_MAP)
    const ncResult = results.find(
      (r) => r.vectorId === 'test.vacuous-nc' && r.phase === 'negative-control',
    )
    expect(ncResult).toBeDefined()
    // The negative control is vacuous — the gate should flag it (pass=false)
    expect(ncResult!.pass).toBe(false)
    expect(ncResult!.error).toMatch(/vacuous/)
  })
})

// ---------------------------------------------------------------------------
// 5. constructSeedTs + checkInvariantTs (unit tests)
// ---------------------------------------------------------------------------

describe('constructSeedTs', () => {
  it('[date-time] $construct recipe builds a Date', () => {
    const recipe = { $construct: 'date-time' as const, args: ['2024-01-15T12:34:56.789Z'] }
    const seed = constructSeedTs(recipe, dateTimeCodec)
    expect(seed).toBeInstanceOf(Date)
    expect((seed as Date).getTime()).toBe(1705322096789)
  })

  it('[byte] $construct recipe builds a Uint8Array', () => {
    const recipe = { $construct: 'byte' as const, args: [[72, 101, 108, 108, 111]] }
    const seed = constructSeedTs(recipe, byteCodec)
    expect(seed).toBeInstanceOf(Uint8Array)
    expect(Buffer.from(seed as Uint8Array).toString('utf-8')).toBe('Hello')
  })

  it('[number-special/NaN] $construct recipe builds NaN', () => {
    const recipe = { $construct: 'number-special' as const, args: ['NaN'] }
    const seed = constructSeedTs(recipe, numberSpecialCodec)
    expect(Number.isNaN(seed as number)).toBe(true)
  })

  it('[int64] plain wire string is decoded to BigInt', () => {
    const seed = constructSeedTs('9007199254740993', int64Codec)
    expect(seed).toBe(BigInt('9007199254740993'))
  })

  it('[decimal] plain wire string is returned as-is (branded string)', () => {
    const seed = constructSeedTs('123.456', decimalCodec)
    expect(seed).toBe('123.456')
  })

  it('[uuid] plain wire string is returned as lowercase', () => {
    const seed = constructSeedTs('550e8400-e29b-41d4-a716-446655440000', uuidCodec)
    expect(seed).toBe('550e8400-e29b-41d4-a716-446655440000')
  })
})

describe('checkInvariantTs', () => {
  it('[/epochMs] valid Date passes', () => {
    const d = new Date('2024-01-15T12:34:56.789Z')
    const err = checkInvariantTs(d, '/epochMs', 1705322096789)
    expect(err).toBeNull()
  })

  it('[/epochMs] wrong epoch ms fails', () => {
    const d = new Date('2024-01-15T12:34:56.789Z')
    const err = checkInvariantTs(d, '/epochMs', 0)
    expect(err).not.toBeNull()
    expect(err).toContain('/epochMs')
  })

  it('[/bigintStr] bigint passes', () => {
    const err = checkInvariantTs(BigInt('9007199254740993'), '/bigintStr', '9007199254740993')
    expect(err).toBeNull()
  })

  it('[/utf8] Uint8Array for "Hello" passes', () => {
    const bytes = new Uint8Array([72, 101, 108, 108, 111])
    const err = checkInvariantTs(bytes, '/utf8', 'Hello')
    expect(err).toBeNull()
  })

  it('[/isNaN] NaN passes', () => {
    const err = checkInvariantTs(NaN, '/isNaN', true)
    expect(err).toBeNull()
  })

  it('[/isNaN] finite number does not satisfy isNaN=true', () => {
    const err = checkInvariantTs(42, '/isNaN', true)
    expect(err).not.toBeNull()
  })

  it('[/isFinite] Infinity does not satisfy isFinite=false', () => {
    const err = checkInvariantTs(Infinity, '/isFinite', false)
    expect(err).toBeNull()
  })
})

// ---------------------------------------------------------------------------
// 6. Host discovery
// ---------------------------------------------------------------------------

describe('getTsHostManifest', () => {
  it('returns a conformant manifest covering all canonical ids', () => {
    const m = getTsHostManifest()
    expect(m.host).toBe('ts')
    expect(m.logicalTypeVersion).toBe(LOGICAL_TYPE_VERSION)
    expect(checkSupportedIds(m)).toHaveLength(0)
  })
})

describe('getPythonHostManifest', () => {
  it('returns a manifest when packages/apigen/python/apigen_logical.py exists', () => {
    const m = getPythonHostManifest(WORKSPACE_ROOT)
    expect(m).not.toBeNull()
    expect(m!.host).toBe('python')
    expect(checkSupportedIds(m!)).toHaveLength(0)
  })

  it('returns null for a workspace root without the Python host', () => {
    const m = getPythonHostManifest('/tmp/nonexistent-workspace-root')
    expect(m).toBeNull()
  })
})

describe('discoverManifestHosts', () => {
  it('returns [] when packages/apigen/hosts does not exist', () => {
    const manifests = discoverManifestHosts('/tmp/nonexistent-workspace-root')
    expect(manifests).toHaveLength(0)
  })

  it('discovers a host-manifest.json when one is written to the hosts dir', () => {
    // Create a temp workspace with a fake host-manifest.json.
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'apigen-gate-test-'))
    const hostsDir = path.join(tmpDir, 'packages', 'apigen', 'hosts', 'my-lang')
    fs.mkdirSync(hostsDir, { recursive: true })

    const fakeManifest: HostManifest = {
      host: 'my-lang',
      logicalTypeVersion: '0.1.0',
      supportedIds: ['date-time', 'int64', 'decimal', 'byte', 'uuid', 'number-special'],
      deps: {},
    }
    fs.writeFileSync(
      path.join(hostsDir, 'host-manifest.json'),
      JSON.stringify(fakeManifest, null, 2),
    )

    const discovered = discoverManifestHosts(tmpDir)
    expect(discovered).toHaveLength(1)
    expect(discovered[0]!.host).toBe('my-lang')
    expect(checkSupportedIds(discovered[0]!)).toHaveLength(0)

    // Cleanup
    fs.rmSync(tmpDir, { recursive: true, force: true })
  })

  it('[TEETH] a generator-scaffolded manifest with empty supportedIds is non-conformant', () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'apigen-gate-test-'))
    const hostsDir = path.join(tmpDir, 'packages', 'apigen', 'hosts', 'go')
    fs.mkdirSync(hostsDir, { recursive: true })

    // This is what `nx generate apigen-nx:host` emits: empty supportedIds
    const scaffoldedManifest: HostManifest = {
      host: 'go',
      logicalTypeVersion: '0.1.0',
      supportedIds: [],
      deps: {},
    }
    fs.writeFileSync(
      path.join(hostsDir, 'host-manifest.json'),
      JSON.stringify(scaffoldedManifest, null, 2),
    )

    const discovered = discoverManifestHosts(tmpDir)
    expect(discovered).toHaveLength(1)
    const errors = checkSupportedIds(discovered[0]!)
    // Empty supportedIds → fails for ALL canonical ids
    expect(errors.length).toBe(CANONICAL_IDS.length)

    fs.rmSync(tmpDir, { recursive: true, force: true })
  })
})

describe('discoverHosts', () => {
  it('always includes the TS host', () => {
    const hosts = discoverHosts(WORKSPACE_ROOT)
    expect(hosts.some((h) => h.manifest.host === 'ts')).toBe(true)
  })

  it('includes the Python host when workspace has apigen_logical.py', () => {
    const hosts = discoverHosts(WORKSPACE_ROOT)
    expect(hosts.some((h) => h.manifest.host === 'python')).toBe(true)
  })

  it('TS host runner is "ts"', () => {
    const hosts = discoverHosts(WORKSPACE_ROOT)
    const ts = hosts.find((h) => h.manifest.host === 'ts')
    expect(ts!.runner).toBe('ts')
  })

  it('Python host runner is "python"', () => {
    const hosts = discoverHosts(WORKSPACE_ROOT)
    const py = hosts.find((h) => h.manifest.host === 'python')
    expect(py!.runner).toBe('python')
  })
})

// ---------------------------------------------------------------------------
// 7. Full matrix — integration: TS + Python pass, red host fails gate
// ---------------------------------------------------------------------------

describe('runConformanceMatrix — integration', () => {
  it('[TS-pass] TS host result has passed=true', () => {
    const results = runConformanceMatrix(WORKSPACE_ROOT)
    const ts = results.find((r) => r.host === 'ts')
    expect(ts).toBeDefined()
    const failures = ts!.results.filter((r) => !r.pass)
    expect(
      failures,
      `TS host failures:\n${failures.map((f) => `  ${f.vectorId} (${f.phase}): ${f.error}`).join('\n')}`,
    ).toHaveLength(0)
    expect(ts!.passed).toBe(true)
  })

  it('[Python-pass] Python host result has passed=true', () => {
    const results = runConformanceMatrix(WORKSPACE_ROOT)
    const py = results.find((r) => r.host === 'python')
    expect(py).toBeDefined()
    const failures = py!.results.filter((r) => !r.pass)
    expect(
      failures,
      `Python host failures:\n${failures.map((f) => `  ${f.vectorId} (${f.phase}): ${f.error}`).join('\n')}`,
    ).toHaveLength(0)
    expect(py!.passed).toBe(true)
  })

  it('[red-host TEETH] a red host (missing supportedIds) makes the matrix non-passing', () => {
    // Simulate a failing host by running checkSupportedIds on an empty manifest.
    const redManifest = emptyManifest('go')
    const errors = checkSupportedIds(redManifest)
    expect(errors.length).toBe(CANONICAL_IDS.length)
    // A real runConformanceMatrix call with this host would have passed=false.
    // We verify the logic directly rather than spinning up a fake workspace.
    const anyError = errors.length > 0
    expect(anyError).toBe(true)
  })

  it('[coverage] both TS and Python hosts are discovered and present in results', () => {
    const results = runConformanceMatrix(WORKSPACE_ROOT)
    const hosts = results.map((r) => r.host)
    expect(hosts).toContain('ts')
    expect(hosts).toContain('python')
  })
})
