import type { PluginInput, PluginOutput } from '@adhd/apigen-core-client';
import { envelopeKey, sanitizeIdentifier } from '@adhd/apigen-engine-naming';
import { HTTP_STATUS } from '@adhd/apigen-base-errors';
import { buildOpPlan } from '@adhd/apigen-engine-runtime';
import type { ProjectionConfig } from '@adhd/apigen-engine-naming';
import { operationFor } from './route';

// ---------------------------------------------------------------------------
// §5 — route + verb derivation (BUG-APIGEN-OPENAPI-ROUTE-PATH-MISMATCH-001):
// serve-core migration — route/verb now come off the resolved `OpPlan`
// (`buildOpPlan`, `@adhd/apigen-engine-runtime`), which calls the same
// `project()`/`@adhd/apigen-engine-naming` derivation `@adhd/apigen-plugin-
// openapi` uses. Generated routes.ts stays byte-identical to what the
// OpenAPI doc advertises for the same operation. `operationFor`
// (`./route.ts`) resolves the `Operation` `buildOpPlan` projects.
//
// DEBT-APIGEN-PLUGIN-MCP-GENERATE-OPERATIONS-001 (RESOLVED): `PluginInput`
// now carries an OPTIONAL `operations?: Operation[]` field
// (`@adhd/apigen-core-client`), threaded through by
// `entrypoint/apigen-cli`'s `orchestrateGenerate()`. `operationFor()` falls
// back to a synthesized single-segment Operation only when a caller builds a
// bare `PluginInput` with no `operations` at all (e.g. a unit test).
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// §9.1 — envelope header key map for code generation
// ---------------------------------------------------------------------------

function envelopeHeaders(
  schema: Record<string, unknown>
): Record<string, string> {
  const inputProps =
    ((schema['input'] as Record<string, unknown> | undefined)?.[
      'properties'
    ] as Record<string, unknown> | undefined) ?? {};
  const meta = schema['x-apigen-envelope'] as
    | Record<string, string>
    | undefined;
  const result: Record<string, string> = {};
  for (const field of Object.keys(inputProps)) {
    if (field === 'data') continue;
    const pluginId = meta?.[field] ?? 'adhd';
    result[field] = envelopeKey(pluginId, field);
  }
  return result;
}

export function generate(input: PluginInput): PluginOutput {
  const port = (input.options['port'] as number) ?? 3000;
  const routePrefix = (input.options['routePrefix'] as string) ?? '';
  const projection =
    (input.options['projection'] as ProjectionConfig | undefined) ?? {};

  const lines: string[] = [
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
    `import express, { Router } from 'express'`,
    `import { dispatch, buildFnTable, coerceQueryParams } from '@adhd/apigen-engine-runtime'`,
  ];
  for (const pkg of input.packages) {
    const varName = sanitizeIdentifier(pkg.id);
    lines.push(`import * as ${varName}_ns from '${pkg.importPath}'`);
    lines.push(
      `const ${varName}_fns = buildFnTable(${varName}_ns as Record<string, unknown>)`
    );
  }
  lines.push(``);
  lines.push(
    `const schemas: Record<string, unknown> = ${JSON.stringify(
      Object.fromEntries(
        input.packages.flatMap((p) =>
          Object.entries(p.schemas).map(([fn, s]) => [
            `${p.id}:${fn}`,
            { schema: s, pkgId: p.id },
          ])
        )
      ),
      null,
      2
    )}`
  );
  lines.push(``);
  lines.push(`const app = express()`);
  lines.push(`app.use(express.json())`);
  lines.push(`const router = Router()`);
  lines.push(``);

  for (const pkg of input.packages) {
    const varName = sanitizeIdentifier(pkg.id);
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      const op = operationFor(
        pkg.id,
        fnName,
        fnSchema as Record<string, unknown>,
        input.operations
      );
      const plan = buildOpPlan({
        op,
        schema: fnSchema,
        transport: 'http',
        projection,
      });
      const route = routePrefix + plan.http.route;
      const verb = plan.http.verb;
      const headerMap = envelopeHeaders(fnSchema as Record<string, unknown>);
      const headerEntries = Object.entries(headerMap);

      if (verb === 'GET') {
        // safe op: domain args from query string, envelope from request headers
        lines.push(`router.get('${route}', async (req, res) => {`);
        if (headerEntries.length > 0) {
          const envParts = headerEntries
            .map(([field, hdr]) => `'${field}': req.headers['${hdr}']`)
            .join(', ');
          lines.push(
            `  const envelope: Record<string, unknown> = { ${envParts} }`
          );
        } else {
          lines.push(`  const envelope: Record<string, unknown> = {}`);
        }
        // FEAT-APIGEN-022: query strings are always strings — coerce to the
        // domain schema's declared number/integer/boolean types before
        // dispatch (never touches POST/body — see coerce-query.ts).
        lines.push(
          `  const domainArgs = coerceQueryParams(req.query as Record<string, unknown>, schemas['${pkg.id}:${fnName}']['schema'] as any)`
        );
        lines.push(
          `  const result = await dispatch(${varName}_fns as any, undefined, schemas['${pkg.id}:${fnName}']['schema'] as any, '${fnName}', envelope, domainArgs as any)`
        );
        lines.push(`  res.json(result)`);
        lines.push(`})`);
      } else {
        // unsafe op: domain args from body.data, envelope from request headers
        lines.push(`router.post('${route}', async (req, res) => {`);
        lines.push(
          `  const { data = {} } = req.body as Record<string, unknown>`
        );
        if (headerEntries.length > 0) {
          const envParts = headerEntries
            .map(([field, hdr]) => `'${field}': req.headers['${hdr}']`)
            .join(', ');
          lines.push(
            `  const envelope: Record<string, unknown> = { ${envParts} }`
          );
        } else {
          lines.push(`  const envelope: Record<string, unknown> = {}`);
        }
        lines.push(
          `  const result = await dispatch(${varName}_fns as any, undefined, schemas['${pkg.id}:${fnName}']['schema'] as any, '${fnName}', envelope, data as any)`
        );
        lines.push(`  res.json(result)`);
        lines.push(`})`);
      }
    }
  }

  lines.push(``);
  lines.push(`app.use(router)`);
  lines.push(`app.listen(${port})`);
  lines.push(``);
  lines.push(`export default router`);

  return { files: [{ path: 'routes.ts', content: lines.join('\n') }] };
}

// Re-export error status map for use in route error handlers (§9).
export { HTTP_STATUS };
