import type {
  Operation,
  PluginInput,
  PluginOutput,
} from '@adhd/apigen-core-client';
import { envelopeKey, sanitizeIdentifier } from '@adhd/apigen-engine-naming';
import { HTTP_STATUS } from '@adhd/apigen-base-errors';
import type { ProjectionConfig } from '@adhd/apigen-engine-naming';
import { buildOperationIndex, resolveRoute } from './route';

// ---------------------------------------------------------------------------
// §5 — route + verb from the canonical `project()` projection
// (BUG-APIGEN-OPENAPI-ROUTE-PATH-MISMATCH-001 / BUG-APIGEN-025 /
// FEAT-APIGEN-022) — see `./route.ts` for the full derivation.
//
// DEBT-APIGEN-PLUGIN-MCP-GENERATE-OPERATIONS-001 (RESOLVED): `PluginInput`
// now carries an OPTIONAL `operations?: Operation[]` field
// (`@adhd/apigen-core-client`), threaded through by
// `entrypoint/apigen-cli`'s `orchestrateGenerate()`. When present, `generate()`
// indexes it via `./route.ts`'s `buildOperationIndex()` — the SAME real
// merged `Operation[]` `run()` already used — for full multi-segment-path
// fidelity. Falls back to the empty index (→ `./route.ts`'s single-segment
// `synthesizeOperation()` reconstruction) only when no `operations` were
// supplied (e.g. a caller/test that builds a bare `PluginInput` directly).
// ---------------------------------------------------------------------------
const NO_OPERATIONS = new Map<string, Operation>();

// ---------------------------------------------------------------------------
// §9.1 — envelope header key map for code generation
// ---------------------------------------------------------------------------

function envelopeHeaders(
  schema: Record<string, unknown>
): Record<string, string> {
  const inputProps =
    ((schema['input'] as Record<string, unknown> | undefined)?.[
      'properties'
    ] as Record<string, unknown> | undefined) ?? {};
  const meta = schema['x-apigen-envelope'] as
    | Record<string, string>
    | undefined;
  const result: Record<string, string> = {};
  for (const field of Object.keys(inputProps)) {
    if (field === 'data') continue;
    const pluginId = meta?.[field] ?? 'adhd';
    result[field] = envelopeKey(pluginId, field);
  }
  return result;
}

export function generate(input: PluginInput): PluginOutput {
  const port = (input.options['port'] as number) ?? 3000;
  const routePrefix = (input.options['routePrefix'] as string) ?? '';
  const projection =
    (input.options['projection'] as ProjectionConfig | undefined) ?? {};
  // DEBT-APIGEN-PLUGIN-MCP-GENERATE-OPERATIONS-001: prefer the real merged
  // Operation[] (now threaded through PluginInput.operations) — falls back
  // to the empty index (single-segment synthesis, see ./route.ts) only when
  // absent.
  const operationIndex = input.operations
    ? buildOperationIndex(input.operations)
    : NO_OPERATIONS;

  const lines: string[] = [
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
    `import express, { Router } from 'express'`,
    `import { dispatch, buildFnTable, coerceQueryParams } from '@adhd/apigen-engine-runtime'`,
  ];
  for (const pkg of input.packages) {
    const varName = sanitizeIdentifier(pkg.id);
    lines.push(`import * as ${varName}_ns from '${pkg.importPath}'`);
    lines.push(
      `const ${varName}_fns = buildFnTable(${varName}_ns as Record<string, unknown>)`
    );
  }
  lines.push(``);
  lines.push(
    `const schemas: Record<string, unknown> = ${JSON.stringify(
      Object.fromEntries(
        input.packages.flatMap((p) =>
          Object.entries(p.schemas).map(([fn, s]) => [
            `${p.id}:${fn}`,
            { schema: s, pkgId: p.id },
          ])
        )
      ),
      null,
      2
    )}`
  );
  lines.push(``);
  lines.push(`const app = express()`);
  lines.push(`app.use(express.json())`);
  lines.push(`const router = Router()`);
  lines.push(``);

  for (const pkg of input.packages) {
    const varName = sanitizeIdentifier(pkg.id);
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      const { route, verb } = resolveRoute(
        pkg.id,
        fnName,
        fnSchema as Record<string, unknown>,
        operationIndex,
        routePrefix,
        projection
      );
      const headerMap = envelopeHeaders(fnSchema as Record<string, unknown>);
      const headerEntries = Object.entries(headerMap);

      if (verb === 'GET') {
        // safe op: domain args from query string, envelope from request headers
        lines.push(`router.get('${route}', async (req, res) => {`);
        if (headerEntries.length > 0) {
          const envParts = headerEntries
            .map(([field, hdr]) => `'${field}': req.headers['${hdr}']`)
            .join(', ');
          lines.push(
            `  const envelope: Record<string, unknown> = { ${envParts} }`
          );
        } else {
          lines.push(`  const envelope: Record<string, unknown> = {}`);
        }
        // FEAT-APIGEN-022: query strings are always strings — coerce to the
        // domain schema's declared number/integer/boolean types before
        // dispatch (never touches POST/body — see coerce-query.ts).
        lines.push(
          `  const domainArgs = coerceQueryParams(req.query as Record<string, unknown>, schemas['${pkg.id}:${fnName}']['schema'] as any)`
        );
        lines.push(
          `  const result = await dispatch(${varName}_fns as any, undefined, schemas['${pkg.id}:${fnName}']['schema'] as any, '${fnName}', envelope, domainArgs as any)`
        );
        lines.push(`  res.json(result)`);
        lines.push(`})`);
      } else {
        // unsafe op: domain args from body.data, envelope from request headers
        lines.push(`router.post('${route}', async (req, res) => {`);
        lines.push(
          `  const { data = {} } = req.body as Record<string, unknown>`
        );
        if (headerEntries.length > 0) {
          const envParts = headerEntries
            .map(([field, hdr]) => `'${field}': req.headers['${hdr}']`)
            .join(', ');
          lines.push(
            `  const envelope: Record<string, unknown> = { ${envParts} }`
          );
        } else {
          lines.push(`  const envelope: Record<string, unknown> = {}`);
        }
        lines.push(
          `  const result = await dispatch(${varName}_fns as any, undefined, schemas['${pkg.id}:${fnName}']['schema'] as any, '${fnName}', envelope, data as any)`
        );
        lines.push(`  res.json(result)`);
        lines.push(`})`);
      }
    }
  }

  lines.push(``);
  lines.push(`app.use(router)`);
  lines.push(`app.listen(${port})`);
  lines.push(``);
  lines.push(`export default router`);

  return { files: [{ path: 'routes.ts', content: lines.join('\n') }] };
}

// Re-export error status map for use in route error handlers (§9).
export { HTTP_STATUS };
