import type { PluginInput, PluginOutput } from '@adhd/apigen-core'
import { needsEnvelopeField, dataParamNames } from '@adhd/apigen-runtime'

export function generate(input: PluginInput): PluginOutput {
  const cliName = (input.options['name'] as string) ?? 'cli'
  const version = (input.options['version'] as string) ?? '0.1.0'

  const lines: string[] = [
    `#!/usr/bin/env node`,
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
    `import { Command } from 'commander'`,
    `import { dispatch } from '@adhd/apigen-runtime'`,
  ]
  for (const pkg of input.packages) {
    lines.push(`import * as ${pkg.id}_fns from '${pkg.importPath}'`)
  }
  lines.push(``)
  lines.push(
    `const schemas: Record<string, unknown> = ${JSON.stringify(
      Object.fromEntries(
        input.packages.flatMap((p) =>
          Object.entries(p.schemas).map(([fn, s]) => [`${p.id}:${fn}`, s]),
        ),
      ),
      null,
      2,
    )}`,
  )
  lines.push(``)
  lines.push(`const program = new Command().name('${cliName}').version('${version}')`)
  lines.push(``)

  for (const pkg of input.packages) {
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      const paramNames = dataParamNames(fnSchema)
      const needsSession = needsEnvelopeField(fnSchema, 'session')
      const dataSchema = (
        (
          (fnSchema.input as Record<string, unknown>)?.['properties'] as Record<string, unknown>
        )?.['data'] as Record<string, unknown> | undefined
      )
      const schemaProps = (
        (dataSchema?.['properties'] as Record<string, { type?: string }>) ?? {}
      )
      const requiredParams = (dataSchema?.['required'] as string[]) ?? []

      lines.push(`program`)
      lines.push(`  .command('${fnName}')`)
      if (needsSession) {
        lines.push(`  .option('--session <key>', 'Session key')`)
      }
      for (const param of paramNames) {
        const isBoolean = schemaProps[param]?.type === 'boolean'
        const isRequired = requiredParams.includes(param)
        if (isBoolean) {
          lines.push(`  .option('--${param}')`)
        } else if (isRequired) {
          lines.push(`  .requiredOption('--${param} <${param}>')`)
        } else {
          lines.push(`  .option('--${param} <${param}>')`)
        }
      }
      lines.push(
        `  .action(async (opts: Record<string, unknown>) => {`,
      )
      lines.push(
        `    const domainArgs: Record<string, unknown> = { ${paramNames
          .map((p) => `'${p}': opts['${p}']`)
          .join(', ')} }`,
      )
      lines.push(
        `    const result = await dispatch(${pkg.id}_fns as any, undefined, schemas['${pkg.id}:${fnName}'] as any, '${fnName}', { session: opts['session'] }, domainArgs)`,
      )
      lines.push(`    console.log(JSON.stringify(result, null, 2))`)
      lines.push(`  })`)
    }
  }

  lines.push(``)
  lines.push(`program.parseAsync()`)

  return { files: [{ path: 'cli.ts', content: lines.join('\n') }] }
}
