import type { PluginInput, PluginOutput } from '@adhd/apigen-core'
import { needsEnvelopeField, dataParamNames } from '@adhd/apigen-runtime'
import { envelopeCliFlag, envelopeEnvVar } from '@adhd/apigen-naming'
import { CLI_EXIT_CODE } from '@adhd/apigen-errors'

// ---------------------------------------------------------------------------
// §9.1 — envelope field binding for CLI (flag + env var per field)
// ---------------------------------------------------------------------------

interface EnvelopeFieldBinding {
  /** The bare field name as it appears in the composed schema. */
  field: string
  /** pluginId resolved from x-apigen-envelope metadata (defaults to 'adhd'). */
  pluginId: string
  /** Generated CLI flag, e.g. '--auth-session' or '--adhd-session'. */
  flag: string
  /** Generated env var, e.g. 'APIGEN_AUTH_SESSION' or 'APIGEN_SESSION'. */
  envVar: string
}

/**
 * Collects all envelope field bindings for a schema, following SPEC §9.1:
 *   flag: --<pluginId>-<field>  +  env: APIGEN_<PLUGINID>_<FIELD>
 *   (flag takes precedence over env when both are present)
 *
 * Reads x-apigen-envelope (Record<field, pluginId>) from the schema;
 * defaults to pluginId='adhd' for any field without an explicit entry.
 */
function envelopeBindings(schema: Record<string, unknown>): EnvelopeFieldBinding[] {
  const inputProps = (
    (schema['input'] as Record<string, unknown> | undefined)?.['properties'] as
      | Record<string, unknown>
      | undefined
  ) ?? {}
  const meta = schema['x-apigen-envelope'] as Record<string, string> | undefined
  const bindings: EnvelopeFieldBinding[] = []
  for (const field of Object.keys(inputProps)) {
    if (field === 'data') continue
    const pluginId = meta?.[field] ?? 'adhd'
    bindings.push({
      field,
      pluginId,
      flag: envelopeCliFlag(pluginId, field),
      envVar: envelopeEnvVar(pluginId, field),
    })
  }
  return bindings
}

export function generate(input: PluginInput): PluginOutput {
  const cliName = (input.options['name'] as string) ?? 'cli'
  const version = (input.options['version'] as string) ?? '0.1.0'

  const lines: string[] = [
    `#!/usr/bin/env node`,
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
    `import { Command } from 'commander'`,
    `import { dispatch, buildFnTable } from '@adhd/apigen-runtime'`,
  ]
  for (const pkg of input.packages) {
    lines.push(`import * as ${pkg.id}_ns from '${pkg.importPath}'`)
    lines.push(`const ${pkg.id}_fns = buildFnTable(${pkg.id}_ns as Record<string, unknown>)`)
  }
  lines.push(``)
  lines.push(
    `const schemas: Record<string, unknown> = ${JSON.stringify(
      Object.fromEntries(
        input.packages.flatMap((p) =>
          Object.entries(p.schemas).map(([fn, s]) => [`${p.id}:${fn}`, s]),
        ),
      ),
      null,
      2,
    )}`,
  )
  lines.push(``)
  lines.push(`const program = new Command().name('${cliName}').version('${version}')`)
  lines.push(``)

  for (const pkg of input.packages) {
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      const paramNames = dataParamNames(fnSchema)
      // Backwards-compatible: keep `needsEnvelopeField` check for legacy 'session' field;
      // the full §9.1 binding handles all envelope fields generically below.
      const needsSession = needsEnvelopeField(fnSchema, 'session')
      const bindings = envelopeBindings(fnSchema as Record<string, unknown>)
      const dataSchema = (
        (
          (fnSchema.input as Record<string, unknown>)?.['properties'] as Record<string, unknown>
        )?.['data'] as Record<string, unknown> | undefined
      )
      const schemaProps = (
        (dataSchema?.['properties'] as Record<string, { type?: string }>) ?? {}
      )
      const requiredParams = (dataSchema?.['required'] as string[]) ?? []

      lines.push(`program`)
      lines.push(`  .command('${fnName}')`)

      // Emit §9.1 envelope flag bindings — each field gets --<pluginId>-<field>
      // (and reads APIGEN_<PLUGINID>_<FIELD> env var when flag is absent).
      for (const b of bindings) {
        // The generated code uses the canonical flag name from §9.1.
        // For backwards-compat, the legacy '--session' case is preserved via
        // needsSession above; if the binding produces '--adhd-session' we skip
        // the old '--session' branch to avoid duplicate flags.
        const flagName = b.flag.replace(/^--/, '') // strip leading '--'
        lines.push(
          `  .option('${b.flag} <${flagName}>', '${b.field} (env: ${b.envVar})')`,
        )
      }

      // Backwards-compat: also emit --session if session is present but was
      // generated by the old code path (needsSession with no binding matching it).
      // This is removed once all callers use x-apigen-envelope metadata.
      // NOTE: if bindings already includes 'session' (as an adhd field), skip this.
      if (needsSession && !bindings.some((b) => b.field === 'session')) {
        lines.push(`  .option('--session <key>', 'Session key')`)
      }

      // Domain params are exposed as kebab-case flags (the CLI convention, and
      // what camelCase param names map to). Commander normalises a `--user-id`
      // flag to the camelCase opt key `userId`, so the flag is kebab while the
      // value is read back via the original camelCase name below.
      const kebab = (p: string) => p.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())
      for (const param of paramNames) {
        const flag = kebab(param)
        const isBoolean = schemaProps[param]?.type === 'boolean'
        const isRequired = requiredParams.includes(param)
        if (isBoolean) {
          lines.push(`  .option('--${flag}')`)
        } else if (isRequired) {
          lines.push(`  .requiredOption('--${flag} <${flag}>')`)
        } else {
          lines.push(`  .option('--${flag} <${flag}>')`)
        }
      }

      lines.push(`  .action(async (opts: Record<string, unknown>) => {`)
      lines.push(
        `    const domainArgs: Record<string, unknown> = { ${paramNames
          .map((p) => `'${p}': opts['${p}']`)
          .join(', ')} }`,
      )

      // §9.1 envelope construction: flag takes precedence over env var.
      if (bindings.length > 0) {
        const envParts = bindings.map((b) => {
          const flagOpt = b.flag.replace(/^--/, '') // e.g. 'auth-session'
          // camelCase the flag option key for commander opts access
          const optKey = flagOpt.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
          return `'${b.field}': opts['${optKey}'] ?? process.env['${b.envVar}']`
        })
        lines.push(`    const envelope: Record<string, unknown> = { ${envParts.join(', ')} }`)
      } else if (needsSession) {
        // Legacy backwards-compat path
        lines.push(
          `    const envelope: Record<string, unknown> = { session: opts['session'] }`,
        )
      } else {
        lines.push(`    const envelope: Record<string, unknown> = {}`)
      }

      lines.push(
        `    const result = await dispatch(${pkg.id}_fns as any, undefined, schemas['${pkg.id}:${fnName}'] as any, '${fnName}', envelope, domainArgs)`,
      )
      // Print the result as single-line JSON so consumers (and tooling) can
      // parse the last stdout line unambiguously; pretty-printing would split
      // the value across lines and defeat line-oriented parsing.
      lines.push(`    console.log(JSON.stringify(result))`)
      lines.push(`  })`)
    }
  }

  lines.push(``)
  lines.push(`program.parseAsync()`)

  return { files: [{ path: 'cli.ts', content: lines.join('\n') }] }
}

// Re-export error exit code map for use in generated CLI error handlers (§9).
export { CLI_EXIT_CODE }
