/** Generates server.ts content for the stdio transport. */
export function generateStdioServer(): string {
  return `// Auto-generated by @adhd/apigen-cli — do not edit
import { Server } from '@modelcontextprotocol/sdk/server/index.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { ListToolsRequestSchema, CallToolRequestSchema } from '@modelcontextprotocol/sdk/types.js'
import { dispatch } from '@adhd/apigen-runtime'
import { toolMetas, groupFns, groupCreateClient } from './index.js'

// §9.1 — extract envelope from MCP _meta["x-<pluginId>-<field>"].
// x-apigen-envelope (field→pluginId map) is carried on each schema entry.
function extractEnvelope(schema: Record<string, unknown>, meta: Record<string, unknown>): Record<string, unknown> {
  const inputProps = ((schema['input'] as any)?.['properties'] as Record<string, unknown>) ?? {}
  const envMeta = schema['x-apigen-envelope'] as Record<string, string> | undefined
  const envelope: Record<string, unknown> = {}
  for (const field of Object.keys(inputProps)) {
    if (field === 'data') continue
    const pluginId = envMeta?.[field] ?? 'adhd'
    const key = \`x-\${pluginId}-\${field}\`
    if (meta[key] !== undefined) envelope[field] = meta[key]
  }
  return envelope
}

const server = new Server({ name: 'apigen-mcp', version: '1.0.0' }, { capabilities: { tools: {} } })

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: Object.entries(toolMetas).map(([name, meta]) => ({
    name,
    description: name,
    inputSchema: (meta.schema as any).input,
  })),
}))

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args = {} } = req.params
  const meta = toolMetas[name]
  if (!meta) throw new Error(\`Unknown tool: \${name}\`)
  // §9.1: envelope from _meta, domain args from data
  const mcpMeta = (args as any)['_meta'] as Record<string, unknown> | undefined ?? {}
  const envelope = extractEnvelope(meta.schema as Record<string, unknown>, mcpMeta)
  const result = await dispatch(
    groupFns[meta.group],
    groupCreateClient[meta.group],
    meta.schema as any,
    name,
    envelope,
    ((args as any)['data'] ?? {}) as Record<string, unknown>,
  )
  return { content: [{ type: 'text', text: JSON.stringify(result) }] }
})

const transport = new StdioServerTransport()
server.connect(transport)
`
}
