/** Generates server.ts content for the stdio transport. */
export function generateStdioServer(): string {
  return `// Auto-generated by @adhd/apigen-cli — do not edit
import { Server } from '@modelcontextprotocol/sdk/server/index.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { ListToolsRequestSchema, CallToolRequestSchema } from '@modelcontextprotocol/sdk/types.js'
import { dispatch } from '@adhd/apigen-runtime'
import { toolMetas, groupFns, groupCreateClient } from './index.js'

const server = new Server({ name: 'apigen-mcp', version: '1.0.0' }, { capabilities: { tools: {} } })

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: Object.entries(toolMetas).map(([name, meta]) => ({
    name,
    description: name,
    inputSchema: (meta.schema as any).input,
  })),
}))

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args = {} } = req.params
  const meta = toolMetas[name]
  if (!meta) throw new Error(\`Unknown tool: \${name}\`)
  const result = await dispatch(
    groupFns[meta.group],
    groupCreateClient[meta.group],
    meta.schema as any,
    name,
    args as Record<string, unknown>,
    ((args as any)['data'] ?? {}) as Record<string, unknown>,
  )
  return { content: [{ type: 'text', text: JSON.stringify(result) }] }
})

const transport = new StdioServerTransport()
server.connect(transport)
`
}
