import type { PluginInput, PluginOutput } from '@adhd/apigen-core-client';
import { needsEnvelopeField, dataParamNames } from '@adhd/apigen-engine-runtime';
import { sanitizeIdentifier } from '@adhd/apigen-engine-naming';
import { CLI_EXIT_CODE } from '@adhd/apigen-base-errors';
import * as path from 'node:path';
import {
  envelopeBindings,
  isJsonTypedProp,
  isBooleanTypedProp,
  dataSchemaProps,
  kebabCase,
} from './schema-introspect';

/**
 * Converts an absolute (or package-name) import path to one relative to
 * {@link outDir}, ensuring the result is suitable for a JS import statement
 * (starts with `'./'` or `'../'`).  Package names (non-absolute) are
 * returned verbatim.
 */
function relativeImportPath(outDir: string, importPath: string): string {
  if (!path.isAbsolute(importPath)) return importPath
  const rel = path.relative(outDir, importPath)
  if (!rel.startsWith('.') && !rel.startsWith('/')) return `./${rel}`
  return rel
}

// BUG-APIGEN-031: the CLI transport's "wire" values are always raw argv
// strings — unlike the HTTP transports (Express/Fastify), which already
// deliver a real parsed array/object from a JSON request body.
// `apigen-base-logical`'s shared decode path (`runmode.ts`'s array/object
// branches) intentionally passes a non-array/non-object wire value straight
// through unchanged, since that's correct for HTTP. For the CLI it means an
// `array`- or `object`-typed domain param's raw `"[10,20,30]"` string reaches
// the target function un-parsed — either a hard crash (`.reduce is not a
// function`) or, worse, a silently wrong answer (string-indexing coincidence,
// e.g. `sorted[idx]` on a 16-char stringified array). Only the CLI plugin
// knows its wire values are string-only, so the JSON.parse belongs here
// (transport-specific), not in the shared decode path. See
// `isJsonTypedProp` (now shared with `run.ts` via `./schema-introspect`).

/** Runtime helper embedded in generated CLI output — see {@link isJsonTypedProp}. */
const JSON_PARSE_ARG_HELPER = [
  `function __apigenParseJsonArg(flag: string, raw: unknown): unknown {`,
  `  if (raw === undefined) return undefined`,
  `  if (typeof raw !== 'string') return raw`,
  `  try {`,
  `    return JSON.parse(raw)`,
  `  } catch (err) {`,
  `    throw new Error(\`Invalid JSON for --\${flag}: \${(err as Error).message}\`)`,
  `  }`,
  `}`,
].join('\n')

export function generate(input: PluginInput): PluginOutput {
  const cliName = (input.options['name'] as string) ?? 'cli';
  const version = (input.options['version'] as string) ?? '0.1.0';

  const usesJsonParseHelper = input.packages.some((pkg) =>
    Object.values(pkg.schemas).some((fnSchema) => {
      const { props: schemaProps } = dataSchemaProps(fnSchema);
      return dataParamNames(fnSchema).some((p) =>
        isJsonTypedProp(schemaProps[p])
      );
    })
  );

  const lines: string[] = [
    `#!/usr/bin/env node`,
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
    `import { Command } from 'commander'`,
    `import { dispatch, buildFnTable } from '@adhd/apigen-engine-runtime'`,
  ];
  for (const pkg of input.packages) {
    const varName = sanitizeIdentifier(pkg.id)
    const importRel = relativeImportPath(input.outputDir, pkg.importPath)
    lines.push(`import * as ${varName}_ns from '${importRel}'`);
    lines.push(
      `const ${varName}_fns = buildFnTable(${varName}_ns as Record<string, unknown>)`
    );
  }
  lines.push(``);
  if (usesJsonParseHelper) {
    lines.push(JSON_PARSE_ARG_HELPER);
    lines.push(``);
  }
  lines.push(
    `const schemas: Record<string, unknown> = ${JSON.stringify(
      Object.fromEntries(
        input.packages.flatMap((p) =>
          Object.entries(p.schemas).map(([fn, s]) => [`${p.id}:${fn}`, s])
        )
      ),
      null,
      2
    )}`
  );
  lines.push(``);
  lines.push(
    `const program = new Command().name('${cliName}').version('${version}')`
  );
  lines.push(``);

  for (const pkg of input.packages) {
    const varName = sanitizeIdentifier(pkg.id)
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      const paramNames = dataParamNames(fnSchema);
      // Backwards-compatible: keep `needsEnvelopeField` check for legacy 'session' field;
      // the full §9.1 binding handles all envelope fields generically below.
      const needsSession = needsEnvelopeField(fnSchema, 'session');
      const bindings = envelopeBindings(fnSchema as Record<string, unknown>);
      const { props: schemaProps, required: requiredParams } =
        dataSchemaProps(fnSchema);

      lines.push(`program`);
      lines.push(`  .command('${fnName}')`);

      // Emit §9.1 envelope flag bindings — each field gets --<pluginId>-<field>
      // (and reads APIGEN_<PLUGINID>_<FIELD> env var when flag is absent).
      for (const b of bindings) {
        // The generated code uses the canonical flag name from §9.1.
        // For backwards-compat, the legacy '--session' case is preserved via
        // needsSession above; if the binding produces '--adhd-session' we skip
        // the old '--session' branch to avoid duplicate flags.
        const flagName = b.flag.replace(/^--/, ''); // strip leading '--'
        lines.push(
          `  .option('${b.flag} <${flagName}>', '${b.field} (env: ${b.envVar})')`
        );
      }

      // Backwards-compat: also emit --session if session is present but was
      // generated by the old code path (needsSession with no binding matching it).
      // This is removed once all callers use x-apigen-envelope metadata.
      // NOTE: if bindings already includes 'session' (as an adhd field), skip this.
      if (needsSession && !bindings.some((b) => b.field === 'session')) {
        lines.push(`  .option('--session <key>', 'Session key')`);
      }

      // Domain params are exposed as kebab-case flags (the CLI convention, and
      // what camelCase param names map to). Commander normalises a `--user-id`
      // flag to the camelCase opt key `userId`, so the flag is kebab while the
      // value is read back via the original camelCase name below.
      const kebab = kebabCase;
      for (const param of paramNames) {
        const flag = kebab(param);
        const isBoolean = isBooleanTypedProp(schemaProps[param]);
        const isRequired = requiredParams.includes(param);
        if (isBoolean) {
          lines.push(`  .option('--${flag}')`);
          // DEBT-APIGEN-CLI-004: when a boolean param defaults to true emit
          // --no-<flag> so Commander generates the negation flag.
          if (schemaProps[param]?.default === true) {
            lines.push(`  .option('--no-${flag}')`);
          }
        } else if (isRequired) {
          lines.push(`  .requiredOption('--${flag} <${flag}>')`);
        } else {
          lines.push(`  .option('--${flag} <${flag}>')`);
        }
      }

      lines.push(`  .action(async (opts: Record<string, unknown>) => {`);
      lines.push(
        `    const domainArgs: Record<string, unknown> = { ${paramNames
          .map((p) =>
            isJsonTypedProp(schemaProps[p])
              ? `'${p}': __apigenParseJsonArg('${kebab(p)}', opts['${p}'])`
              : `'${p}': opts['${p}']`
          )
          .join(', ')} }`
      );

      // §9.1 envelope construction: flag takes precedence over env var.
      if (bindings.length > 0) {
        const envParts = bindings.map((b) => {
          const flagOpt = b.flag.replace(/^--/, ''); // e.g. 'auth-session'
          // camelCase the flag option key for commander opts access
          const optKey = flagOpt.replace(/-([a-z])/g, (_, c: string) =>
            c.toUpperCase()
          );
          return `'${b.field}': opts['${optKey}'] ?? process.env['${b.envVar}']`;
        });
        lines.push(
          `    const envelope: Record<string, unknown> = { ${envParts.join(
            ', '
          )} }`
        );
      } else if (needsSession) {
        // Legacy backwards-compat path
        lines.push(
          `    const envelope: Record<string, unknown> = { session: opts['session'] }`
        );
      } else {
        lines.push(`    const envelope: Record<string, unknown> = {}`);
      }

      lines.push(
        `    const result = await dispatch(${varName}_fns as any, undefined, schemas['${pkg.id}:${fnName}'] as any, '${fnName}', envelope, domainArgs)`
      );
      // Print the result as single-line JSON so consumers (and tooling) can
      // parse the last stdout line unambiguously; pretty-printing would split
      // the value across lines and defeat line-oriented parsing.
      lines.push(`    console.log(JSON.stringify(result))`);
      lines.push(`  })`);
    }
  }

  lines.push(``);
  lines.push(`program.parseAsync()`);

  return { files: [{ path: 'cli.ts', content: lines.join('\n') }] };
}

// Re-export error exit code map for use in generated CLI error handlers (§9).
export { CLI_EXIT_CODE };
