import type { PluginInput, PluginOutput } from '@adhd/apigen-core-client';
import { needsEnvelopeField, dataParamNames } from '@adhd/apigen-engine-runtime';
import { sanitizeIdentifier } from '@adhd/apigen-engine-naming';
import { CLI_EXIT_CODE } from '@adhd/apigen-base-errors';
import * as path from 'node:path';
import {
  envelopeBindings,
  isJsonTypedProp,
  isBooleanTypedProp,
  dataSchemaProps,
  resolveRootUnion,
  kebabCase,
} from './schema-introspect';
import type { EnvelopeFieldBinding, FlagProp, RootUnionSchema } from './schema-introspect';

/**
 * Converts an absolute (or package-name) import path to one relative to
 * {@link outDir}, ensuring the result is suitable for a JS import statement
 * (starts with `'./'` or `'../'`).  Package names (non-absolute) are
 * returned verbatim.
 */
function relativeImportPath(outDir: string, importPath: string): string {
  if (!path.isAbsolute(importPath)) return importPath
  const rel = path.relative(outDir, importPath)
  if (!rel.startsWith('.') && !rel.startsWith('/')) return `./${rel}`
  return rel
}

// BUG-APIGEN-031: the CLI transport's "wire" values are always raw argv
// strings — unlike the HTTP transports (Express/Fastify), which already
// deliver a real parsed array/object from a JSON request body.
// `apigen-base-logical`'s shared decode path (`runmode.ts`'s array/object
// branches) intentionally passes a non-array/non-object wire value straight
// through unchanged, since that's correct for HTTP. For the CLI it means an
// `array`- or `object`-typed domain param's raw `"[10,20,30]"` string reaches
// the target function un-parsed — either a hard crash (`.reduce is not a
// function`) or, worse, a silently wrong answer (string-indexing coincidence,
// e.g. `sorted[idx]` on a 16-char stringified array). Only the CLI plugin
// knows its wire values are string-only, so the JSON.parse belongs here
// (transport-specific), not in the shared decode path. See
// `isJsonTypedProp` (now shared with `run.ts` via `./schema-introspect`).

/** Runtime helper embedded in generated CLI output — see {@link isJsonTypedProp}. */
const JSON_PARSE_ARG_HELPER = [
  `function __apigenParseJsonArg(flag: string, raw: unknown): unknown {`,
  `  if (raw === undefined) return undefined`,
  `  if (typeof raw !== 'string') return raw`,
  `  try {`,
  `    return JSON.parse(raw)`,
  `  } catch (err) {`,
  `    throw new Error(\`Invalid JSON for --\${flag}: \${(err as Error).message}\`)`,
  `  }`,
  `}`,
].join('\n')

// ---------------------------------------------------------------------------
// BUG-APIGEN-CLI-ROOT-ONEOF-UNSUPPORTED-001 — shared flag/action emission,
// factored out of the per-operation loop so both the flat (`{type:'object',
// properties:{...}}`) case AND each branch of a root-level `oneOf`+
// `discriminator` domain schema (see `resolveRootUnion`) render flags via the
// IDENTICAL logic. Once inside one discriminator branch, its own `properties`
// is flat again — no new flag-typing logic is needed there, only reuse.
// ---------------------------------------------------------------------------

/** Emits the §9.1 envelope flag bindings (+ legacy `--session` fallback) for one (sub)command. */
function emitEnvelopeFlags(
  lines: string[],
  bindings: EnvelopeFieldBinding[],
  needsSession: boolean
): void {
  // Emit §9.1 envelope flag bindings — each field gets --<pluginId>-<field>
  // (and reads APIGEN_<PLUGINID>_<FIELD> env var when flag is absent).
  for (const b of bindings) {
    // The generated code uses the canonical flag name from §9.1.
    // For backwards-compat, the legacy '--session' case is preserved via
    // needsSession above; if the binding produces '--adhd-session' we skip
    // the old '--session' branch to avoid duplicate flags.
    const flagName = b.flag.replace(/^--/, ''); // strip leading '--'
    lines.push(
      `  .option('${b.flag} <${flagName}>', '${b.field} (env: ${b.envVar})')`
    );
  }

  // Backwards-compat: also emit --session if session is present but was
  // generated by the old code path (needsSession with no binding matching it).
  // This is removed once all callers use x-apigen-envelope metadata.
  // NOTE: if bindings already includes 'session' (as an adhd field), skip this.
  if (needsSession && !bindings.some((b) => b.field === 'session')) {
    lines.push(`  .option('--session <key>', 'Session key')`);
  }
}

/** Emits one `--<flag>` (or `.requiredOption`) per domain param for one (sub)command. */
function emitParamFlags(
  lines: string[],
  paramNames: string[],
  schemaProps: Record<string, FlagProp>,
  requiredParams: string[]
): void {
  // Domain params are exposed as kebab-case flags (the CLI convention, and
  // what camelCase param names map to). Commander normalises a `--user-id`
  // flag to the camelCase opt key `userId`, so the flag is kebab while the
  // value is read back via the original camelCase name below.
  for (const param of paramNames) {
    const flag = kebabCase(param);
    const isBoolean = isBooleanTypedProp(schemaProps[param]);
    const isRequired = requiredParams.includes(param);
    if (isBoolean) {
      lines.push(`  .option('--${flag}')`);
      // DEBT-APIGEN-CLI-004: when a boolean param defaults to true emit
      // --no-<flag> so Commander generates the negation flag.
      if (schemaProps[param]?.default === true) {
        lines.push(`  .option('--no-${flag}')`);
      }
    } else if (isRequired) {
      lines.push(`  .requiredOption('--${flag} <${flag}>')`);
    } else {
      lines.push(`  .option('--${flag} <${flag}>')`);
    }
  }
}

/**
 * Codegen-internal key for a discriminator branch's own synthesized
 * `ComposedSchemas` entry (registered in the emitted `schemas` const
 * alongside the real per-operation entries) — see the doc comment on
 * {@link emitDiscriminatedCommand} for why this is needed.
 */
function branchDispatchSchemaKey(
  pkgId: string,
  fnName: string,
  commandName: string
): string {
  return `${pkgId}:${fnName}::${commandName}`;
}

interface DispatchActionParams {
  varName: string;
  /**
   * The `schemas[...]` lookup key `dispatch()` validates/decodes
   * `domainArgs` against. Defaults to `${pkgId}:${fnName}` (the flat case)
   * when omitted; a discriminator branch passes its own
   * {@link branchDispatchSchemaKey} instead — see
   * {@link emitDiscriminatedCommand}.
   */
  dispatchSchemaKey?: string;
  pkgId: string;
  fnName: string;
  bindings: EnvelopeFieldBinding[];
  needsSession: boolean;
  paramNames: string[];
  schemaProps: Record<string, FlagProp>;
  /**
   * Extra literal `domainArgs` entries emitted ahead of the flag-derived
   * ones — used to bind a discriminator branch's literal value (e.g.
   * `{ operation: 'createItem' }`) without exposing it as a CLI flag; the
   * value is already source-text (pre-`JSON.stringify`'d), not raw.
   */
  literalDomainArgs?: Record<string, string>;
}

/** Emits the `.action(...)` block that builds `domainArgs`/`envelope` and dispatches. */
function emitDispatchAction(lines: string[], params: DispatchActionParams): void {
  const {
    varName,
    pkgId,
    fnName,
    bindings,
    needsSession,
    paramNames,
    schemaProps,
    literalDomainArgs,
  } = params;
  const dispatchSchemaKey = params.dispatchSchemaKey ?? `${pkgId}:${fnName}`;

  lines.push(`  .action(async (opts: Record<string, unknown>) => {`);
  const literalParts = Object.entries(literalDomainArgs ?? {}).map(
    ([field, valueSrc]) => `'${field}': ${valueSrc}`
  );
  const flagParts = paramNames.map((p) =>
    isJsonTypedProp(schemaProps[p])
      ? `'${p}': __apigenParseJsonArg('${kebabCase(p)}', opts['${p}'])`
      : `'${p}': opts['${p}']`
  );
  lines.push(
    `    const domainArgs: Record<string, unknown> = { ${[
      ...literalParts,
      ...flagParts,
    ].join(', ')} }`
  );

  // §9.1 envelope construction: flag takes precedence over env var.
  if (bindings.length > 0) {
    const envParts = bindings.map((b) => {
      const flagOpt = b.flag.replace(/^--/, ''); // e.g. 'auth-session'
      // camelCase the flag option key for commander opts access
      const optKey = flagOpt.replace(/-([a-z])/g, (_, c: string) =>
        c.toUpperCase()
      );
      return `'${b.field}': opts['${optKey}'] ?? process.env['${b.envVar}']`;
    });
    lines.push(
      `    const envelope: Record<string, unknown> = { ${envParts.join(', ')} }`
    );
  } else if (needsSession) {
    // Legacy backwards-compat path
    lines.push(
      `    const envelope: Record<string, unknown> = { session: opts['session'] }`
    );
  } else {
    lines.push(`    const envelope: Record<string, unknown> = {}`);
  }

  lines.push(
    `    const result = await dispatch(${varName}_fns as any, undefined, schemas['${dispatchSchemaKey}'] as any, '${fnName}', envelope, domainArgs)`
  );
  // Print the result as single-line JSON so consumers (and tooling) can
  // parse the last stdout line unambiguously; pretty-printing would split
  // the value across lines and defeat line-oriented parsing.
  lines.push(`    console.log(JSON.stringify(result))`);
  lines.push(`  })`);
}

/**
 * BUG-APIGEN-CLI-ROOT-ONEOF-UNSUPPORTED-001: renders an operation whose
 * domain schema is a root-level `oneOf`+`discriminator` union (e.g. the
 * shipped `apigen-plugin-batch`'s `_batch/<kind>` mount, via
 * `apigen-core-client`'s `buildBatchKindSchema`) as N Commander subcommands —
 * one per discriminator branch (`<cli> <fnName> <branch> --flag ...`) — since
 * there is no single flat `properties` map to iterate for the operation as a
 * whole. The discriminator's own literal-value field (e.g. `operation`) is
 * bound automatically from the matched branch rather than exposed as a flag
 * — it is implied by which subcommand the caller invoked.
 *
 * Each branch dispatches against its OWN synthesized, flat
 * `{data:{properties:branch.props}}` schema entry (registered under
 * {@link branchDispatchSchemaKey}, alongside the real per-operation schema
 * in the emitted `schemas` const) rather than the whole-operation `oneOf`
 * schema. `dispatch()`/`dataParamNames()` (`@adhd/apigen-engine-runtime`)
 * still assume a flat `data.properties` map — by construction, exactly the
 * SAME assumption every non-union operation already satisfies — so this
 * keeps them correct and unmodified for a root-union branch too, with zero
 * changes needed there. The discriminator field is included in the branch's
 * own synthesized schema (so it round-trips positionally to the target fn
 * alongside the branch's other domain params); it is simply not exposed as
 * a CLI flag on the emitted command.
 */
function emitDiscriminatedCommand(
  lines: string[],
  params: {
    varName: string;
    pkgId: string;
    fnName: string;
    bindings: EnvelopeFieldBinding[];
    needsSession: boolean;
    rootUnion: RootUnionSchema;
  }
): void {
  const { varName, pkgId, fnName, bindings, needsSession, rootUnion } = params;
  const parentVar = sanitizeIdentifier(`${pkgId}_${fnName}_cmd`);
  lines.push(`const ${parentVar} = program.command('${fnName}')`);

  for (const branch of rootUnion.branches) {
    const flagParamNames = Object.keys(branch.props).filter(
      (p) => p !== rootUnion.discriminatorProperty
    );
    const requiredParams = branch.required.filter(
      (p) => p !== rootUnion.discriminatorProperty
    );

    lines.push(`${parentVar}`);
    lines.push(`  .command('${branch.commandName}')`);
    emitEnvelopeFlags(lines, bindings, needsSession);
    emitParamFlags(lines, flagParamNames, branch.props, requiredParams);
    emitDispatchAction(lines, {
      varName,
      pkgId,
      fnName,
      dispatchSchemaKey: branchDispatchSchemaKey(
        pkgId,
        fnName,
        branch.commandName
      ),
      bindings,
      needsSession,
      paramNames: flagParamNames,
      schemaProps: branch.props,
      literalDomainArgs: {
        [rootUnion.discriminatorProperty]: JSON.stringify(branch.value),
      },
    });
  }
}

// serve-core migration (cli-adapter): `generate()` renders static TypeScript
// SOURCE TEXT from a bare composed schema (no live `Operation`/`OpPlan`
// available at codegen time), so it keeps consuming `./schema-introspect`'s
// flag/envelope helpers directly rather than `OpPlan.cliFlags` — see that
// module's header comment for why, and why the two must be kept in sync.
// The LIVE `run()` path (this package's other consumer of these decisions)
// has migrated onto `@adhd/apigen-engine-runtime`'s `buildOpPlan` instead.
export function generate(input: PluginInput): PluginOutput {
  const cliName = (input.options['name'] as string) ?? 'cli';
  const version = (input.options['version'] as string) ?? '0.1.0';

  const usesJsonParseHelper = input.packages.some((pkg) =>
    Object.values(pkg.schemas).some((fnSchema) => {
      const rootUnion = resolveRootUnion(fnSchema);
      if (rootUnion) {
        return rootUnion.branches.some((branch) =>
          Object.keys(branch.props)
            .filter((p) => p !== rootUnion.discriminatorProperty)
            .some((p) => isJsonTypedProp(branch.props[p]))
        );
      }
      const { props: schemaProps } = dataSchemaProps(fnSchema);
      return dataParamNames(fnSchema).some((p) =>
        isJsonTypedProp(schemaProps[p])
      );
    })
  );

  const lines: string[] = [
    `#!/usr/bin/env node`,
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
    `import { Command } from 'commander'`,
    `import { dispatch, buildFnTable } from '@adhd/apigen-engine-runtime'`,
  ];
  for (const pkg of input.packages) {
    const varName = sanitizeIdentifier(pkg.id)
    const importRel = relativeImportPath(input.outputDir, pkg.importPath)
    lines.push(`import * as ${varName}_ns from '${importRel}'`);
    lines.push(
      `const ${varName}_fns = buildFnTable(${varName}_ns as Record<string, unknown>)`
    );
  }
  lines.push(``);
  if (usesJsonParseHelper) {
    lines.push(JSON_PARSE_ARG_HELPER);
    lines.push(``);
  }
  const schemasMap: Record<string, unknown> = Object.fromEntries(
    input.packages.flatMap((p) =>
      Object.entries(p.schemas).map(([fn, s]) => [`${p.id}:${fn}`, s])
    )
  );
  // BUG-APIGEN-CLI-ROOT-ONEOF-UNSUPPORTED-001: register one additional,
  // codegen-internal, synthesized flat schema PER discriminator branch — see
  // {@link emitDiscriminatedCommand}'s doc comment for why `dispatch()` needs
  // a flat per-branch schema (not the whole-operation `oneOf`) to resolve
  // `domainArgs` correctly, unmodified.
  for (const pkg of input.packages) {
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      const rootUnion = resolveRootUnion(fnSchema);
      if (!rootUnion) continue;
      for (const branch of rootUnion.branches) {
        const key = branchDispatchSchemaKey(pkg.id, fnName, branch.commandName);
        schemasMap[key] = {
          input: {
            type: 'object',
            properties: {
              data: {
                type: 'object',
                properties: branch.props,
                additionalProperties: false,
                ...(branch.required.length > 0
                  ? { required: branch.required }
                  : {}),
              },
            },
            required: ['data'],
          },
          // Output encoding is orthogonal to this bug (input-flag emission);
          // pass through unencoded rather than the whole operation's own
          // (possibly also `oneOf`-shaped) output schema.
          output: {},
          ...(fnSchema.hasCtx ? { hasCtx: true } : {}),
        };
      }
    }
  }
  lines.push(
    `const schemas: Record<string, unknown> = ${JSON.stringify(
      schemasMap,
      null,
      2
    )}`
  );
  lines.push(``);
  lines.push(
    `const program = new Command().name('${cliName}').version('${version}')`
  );
  lines.push(``);

  for (const pkg of input.packages) {
    const varName = sanitizeIdentifier(pkg.id)
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      // Backwards-compatible: keep `needsEnvelopeField` check for legacy 'session' field;
      // the full §9.1 binding handles all envelope fields generically below.
      const needsSession = needsEnvelopeField(fnSchema, 'session');
      const bindings = envelopeBindings(fnSchema as Record<string, unknown>);

      // BUG-APIGEN-CLI-ROOT-ONEOF-UNSUPPORTED-001: an operation whose domain
      // schema is a root-level `oneOf`+`discriminator` union (e.g. batch's
      // `_batch/<kind>` mount) has no flat `properties` map to iterate — it
      // renders as N Commander subcommands, one per discriminator branch,
      // instead of the single flat-flags command below.
      const rootUnion = resolveRootUnion(fnSchema);
      if (rootUnion) {
        emitDiscriminatedCommand(lines, {
          varName,
          pkgId: pkg.id,
          fnName,
          bindings,
          needsSession,
          rootUnion,
        });
        continue;
      }

      const paramNames = dataParamNames(fnSchema);
      const { props: schemaProps, required: requiredParams } =
        dataSchemaProps(fnSchema);

      lines.push(`program`);
      lines.push(`  .command('${fnName}')`);
      emitEnvelopeFlags(lines, bindings, needsSession);
      emitParamFlags(lines, paramNames, schemaProps, requiredParams);
      emitDispatchAction(lines, {
        varName,
        pkgId: pkg.id,
        fnName,
        bindings,
        needsSession,
        paramNames,
        schemaProps,
      });
    }
  }

  lines.push(``);
  lines.push(`program.parseAsync()`);

  return { files: [{ path: 'cli.ts', content: lines.join('\n') }] };
}

// Re-export error exit code map for use in generated CLI error handlers (§9).
export { CLI_EXIT_CODE };
