import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { db } from "./client.js";

/**
 * Runs pending Drizzle migrations synchronously before the server starts.
 * Migrations are read from the ./drizzle folder (generated by drizzle-kit).
 */
export function runMigrations(): void {
    migrate(db, {
        migrationsFolder: new URL(
            "../../drizzle",
            import.meta.url
        ).pathname
    });
}
