// @adhd/apigen-plugin-ts-types — hand-rolled JSON-Schema → TS type-declaration
// emitter (FEAT-APIGEN-TS-TYPE-CODEGEN-001, SPEC §6.1).
//
// Round-1 scope: primitives, `const` literals, literal enums, arrays, named
// object interfaces (required/optional members; nested objects → named support
// types), `$ref`/`definitions`/`$defs`, and `oneOf` + `discriminator`
// discriminated unions. Every construct outside that subset THROWS
// `[apigen-plugin-ts-types] … not supported (round 1)` carrying the fn + JSON
// property path — the emitter never degrades to `any`/`unknown`/bare `object`
// in the discriminated-union path.
//
// The functions in this module are pure (schema in → string out) and exported
// for direct unit testing; `plugin.ts` wires them into the `OutputPlugin`.

import { tokenize } from '@adhd/apigen-core-client';
import { sanitizeIdentifier, toPascal } from '@adhd/apigen-engine-naming';

/** A JSON-Schema node, modeled as an open record (matches `JSONSchema`). */
type Schema = Record<string, unknown>;

/** Mutable state threaded through one `emitFnTypes` call. */
interface EmitContext {
  /** Sanitized PascalCase package prefix, e.g. `'DispatchCli'`. */
  pkgPrefix: string;
  /** Function name (for error messages). */
  fnName: string;
  /** Hoisted `definitions`/`$defs` keyed by sanitized key (merged, later-wins). */
  defs: Map<string, Schema>;
  /** Declarations in emission order (interfaces, union types, type aliases). */
  decls: string[];
  /** Names already declared — duplicate + recursion guard. */
  declared: Set<string>;
}

const PRIMITIVES: Record<string, string> = {
  string: 'string',
  number: 'number',
  integer: 'number',
  boolean: 'boolean',
  null: 'null',
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Build the sanitized, PascalCase package prefix used in every emitted type
 * name — e.g. `'dispatch-cli'` → `'DispatchCli'` (hyphenated package ids are
 * the monorepo norm; see BUG-APIGEN-032 for why sanitization is load-bearing).
 */
export function pkgPrefixFor(pkgId: string): string {
  return sanitizeIdentifier(toPascal({ raw: pkgId, words: tokenize(pkgId) }));
}

/**
 * Emit the fully package-qualified type name for a function's Input/Output
 * type: `sanitizeIdentifier(toPascal({raw, words: tokenize(raw)}))` under the
 * already-sanitized `pkgPrefix`. E.g.
 * `typeName('DispatchCli', 'validate', 'Output')` → `DispatchCliValidateOutput`.
 */
export function typeName(
  pkgPrefix: string,
  raw: string,
  suffix: 'Input' | 'Output'
): string {
  const fn = sanitizeIdentifier(toPascal({ raw, words: tokenize(raw) }));
  return `${pkgPrefix}${fn}${suffix}`;
}

/**
 * Strip the composed `data` envelope (invariant `data-wrapper-always-present`)
 * from a composed `pkg.schemas[fn].input` schema, returning the bare domain
 * params object. A no-op for schemas that are not data-wrapped (e.g. `op.input`
 * from the v2 descriptor, which is already data-dissolved).
 */
export function unwrapDataWrapper(input: unknown): unknown {
  if (typeof input !== 'object' || input === null) return input;
  const schema = input as Schema;
  const properties = schema['properties'];
  if (typeof properties === 'object' && properties !== null) {
    const data = (properties as Record<string, unknown>)['data'];
    if (typeof data === 'object' && data !== null) return data;
  }
  return input;
}

/**
 * Emit the full file content for one function: a generated-header comment plus
 * one declaration per named type (interface / union / alias) for the function's
 * Input and Output, derived from the function's JSON-Schema IR. Never inline
 * anonymous objects; never `any`/`unknown`/bare `object` in the union path.
 *
 * @throws `Error` with a `[apigen-plugin-ts-types]` prefix and
 *         `(fn: <fnName>, path: <property-path>)` on any unsupported construct.
 */
export function emitFnTypes(
  pkgPrefix: string,
  fnName: string,
  schema: { input: unknown; output: unknown }
): string {
  const ctx: EmitContext = {
    pkgPrefix,
    fnName,
    defs: new Map(),
    decls: [],
    declared: new Set(),
  };
  hoistDefs(ctx, schema.input);
  hoistDefs(ctx, schema.output);

  emitRoot(schema.input, typeName(pkgPrefix, fnName, 'Input'), ctx, 'input');
  emitRoot(schema.output, typeName(pkgPrefix, fnName, 'Output'), ctx, 'output');

  const lines = [
    '/**',
    " * Generated by apigen (ts-types plugin) from the function's JSON-Schema IR.",
    ' * Do not edit by hand.',
    ' */',
  ];
  for (const decl of ctx.decls) lines.push('', decl);
  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Roots — top-level Input/Output declarations
// ---------------------------------------------------------------------------

/**
 * Emit the top-level declaration for the function's Input or Output schema.
 * Objects with properties become named `interface`s, `oneOf`+`discriminator`
 * become named union types, everything else becomes a named type alias.
 */
function emitRoot(
  schema: unknown,
  name: string,
  ctx: EmitContext,
  path: string
): void {
  const s = schema as Schema;
  checkRejections(s, path, ctx);

  if (typeof s['$ref'] === 'string') {
    const refName = emitRef(s['$ref'], path, ctx);
    ctx.decls.push(`export type ${name} = ${refName};`);
    return;
  }
  if (s['oneOf'] !== undefined) {
    const nullIdx = indexOfNullBranch(s);
    if (nullIdx >= 0) {
      // Root nullable union (e.g. `Promise<Task | null>`) → a type alias whose
      // object branches get `<RootName>Item` names (never a self-reference).
      const branches = (s['oneOf'] as Schema[]).filter((_, i) => i !== nullIdx);
      const exprs = branches.map((b, i) => {
        const branchName =
          branches.length > 1 ? `${name}Item${i}` : `${name}Item`;
        return emitTypeExpr(b, { name: branchName, path: `${path}[${i}]` }, ctx);
      });
      ctx.decls.push(`export type ${name} = ${exprs.join(' | ')} | null;`);
      return;
    }
    emitNamedUnion(s, name, ctx, path);
    return;
  }
  if (isObjectSchema(s) && hasProperties(s)) {
    emitNamedObject(s, name, ctx, path);
    return;
  }

  let expr: string;
  if (s['type'] === 'array') {
    // Root array-of-object: name the element interface `<RootName>Item`.
    const itemsName = `${name}Item`;
    const inner = emitTypeExpr(
      (s['items'] as Schema | undefined) ?? {},
      { name: itemsName, path: `${path}[]` },
      ctx
    );
    expr = `${inner}[]`;
  } else {
    expr = emitTypeExpr(s, { name, path }, ctx);
  }
  ctx.decls.push(`export type ${name} = ${expr};`);
}

// ---------------------------------------------------------------------------
// Member-position type expressions
// ---------------------------------------------------------------------------

/**
 * Emit a type expression for a member/position that is NOT a top-level
 * Input/Output: primitives, literals, arrays, `$ref` names, `Record`/`unknown`,
 * and — when the schema is an object or a discriminated union — queue the
 * named interface/union into `ctx.decls` and return its name.
 *
 * @param hint.name the name to give an object/union type encountered here
 *                  (nested objects → `<parentName><Pascal(prop)>`, arrays of
 *                  objects reuse the position name with `[]` wrapped around it)
 */
function emitTypeExpr(
  schema: unknown,
  hint: { name: string; path: string },
  ctx: EmitContext
): string {
  const s = schema as Schema;
  checkRejections(s, hint.path, ctx);

  if (typeof s['$ref'] === 'string') return emitRef(s['$ref'], hint.path, ctx);
  if (s['oneOf'] !== undefined) {
    // Nullable-union spelling (extractor emits optional/nullable members as
    // `oneOf: [T, { type: 'null' }]` without a discriminator — e.g. the
    // fixture's `name?: string`) → faithful `<rest> | null`. Everything else
    // without a discriminator is a genuine untagged union → REJECT.
    const nullIdx = indexOfNullBranch(s);
    if (nullIdx >= 0) {
      const branches = (s['oneOf'] as Schema[]).filter((_, i) => i !== nullIdx);
      const exprs = branches.map((b, i) => {
        const branchName =
          branches.length > 1 ? `${hint.name}${i}` : hint.name;
        return emitTypeExpr(b, { name: branchName, path: `${hint.path}[${i}]` }, ctx);
      });
      return `${exprs.join(' | ')} | null`;
    }
    return emitNamedUnion(s, hint.name, ctx, hint.path);
  }
  if ('const' in s) return emitConst(s, hint.path, ctx);
  if (Array.isArray(s['enum'])) return emitEnum(s, hint.path, ctx);

  if (isObjectSchema(s)) {
    if (hasProperties(s)) return emitNamedObject(s, hint.name, ctx, hint.path);
    return 'Record<string, unknown>';
  }

  if (s['type'] === 'array') {
    const inner = emitTypeExpr(
      (s['items'] as Schema | undefined) ?? {},
      { name: hint.name, path: `${hint.path}[]` },
      ctx
    );
    return `${inner}[]`;
  }

  if (typeof s['type'] === 'string') {
    const prim = PRIMITIVES[s['type']];
    if (prim) return prim;
    throw reject(ctx, `unsupported type construct "${s['type']}"`, hint.path);
  }
  if (s['type'] !== undefined) {
    // e.g. `type: ['string', 'null']` — a multi-type union spelling.
    throw reject(
      ctx,
      `unsupported type construct ${JSON.stringify(s['type'])}`,
      hint.path
    );
  }

  // `{}` — no `type`, no other construct.
  return 'unknown';
}

// ---------------------------------------------------------------------------
// Named type emission (interfaces / unions) + support types
// ---------------------------------------------------------------------------

/** Emit a named object schema as `export interface <name> { … }`. */
function emitNamedObject(
  schema: Schema,
  name: string,
  ctx: EmitContext,
  path: string
): string {
  if (ctx.declared.has(name)) return name;
  ctx.declared.add(name);
  const members = emitObjectMembers(schema, name, ctx, path);
  const body = members.length > 0 ? `\n${members.join('\n')}\n` : '';
  ctx.decls.push(`export interface ${name} {${body}}`);
  return name;
}

/**
 * Emit a `oneOf` + `discriminator` schema as a named discriminated union:
 * `export type <name> = <Branch0> | <Branch1>;` followed by one named
 * interface per branch, each retaining its discriminant literal member. The
 * union type declaration precedes its branches to mirror SPEC §6.1.
 *
 * Branch names come from `discriminator.mapping` keys whose pointers end in
 * `/oneOf/<i>` (`<name><Pascal(key)>`); unmatched branches fall back to
 * `<name>Branch<i>`. A non-object branch REJECTS — never `any`/`unknown`.
 */
function emitNamedUnion(
  schema: Schema,
  unionName: string,
  ctx: EmitContext,
  path: string
): string {
  if (ctx.declared.has(unionName)) return unionName;
  const oneOf = schema['oneOf'];
  if (!Array.isArray(oneOf) || oneOf.length === 0) {
    throw reject(ctx, 'oneOf must be a non-empty array', path);
  }
  const disc = schema['discriminator'];
  if (
    typeof disc !== 'object' ||
    disc === null ||
    !(disc as Record<string, unknown>)['propertyName']
  ) {
    throw reject(ctx, 'oneOf without discriminator is not supported (round 1)', path);
  }
  ctx.declared.add(unionName);

  const discRecord = disc as Record<string, unknown>;
  const mapping =
    typeof discRecord['mapping'] === 'object' && discRecord['mapping'] !== null
      ? (discRecord['mapping'] as Record<string, unknown>)
      : undefined;
  const nameByIndex: Record<number, string> = {};
  if (mapping) {
    for (const [key, ptr] of Object.entries(mapping)) {
      const m = /\/oneOf\/(\d+)$/.exec(String(ptr));
      if (m) {
        nameByIndex[Number(m[1])] =
          unionName +
          sanitizeIdentifier(toPascal({ raw: key, words: tokenize(key) }));
      }
    }
  }

  // Validate every branch up front so the union decl below never lists a
  // branch that later fails to emit.
  const branchNames: string[] = [];
  oneOf.forEach((branchSchema, i) => {
    const branch = branchSchema as Schema;
    if (!isObjectSchema(branch) || !hasProperties(branch)) {
      throw reject(
        ctx,
        'oneOf branch is not an object schema (discriminated union)',
        `${path}[${i}]`
      );
    }
    branchNames.push(nameByIndex[i] ?? `${unionName}Branch${i}`);
  });

  // Union first, branches after — matches SPEC §6.1's example layout.
  ctx.decls.push(`export type ${unionName} = ${branchNames.join(' | ')};`);
  oneOf.forEach((branchSchema, i) => {
    emitNamedObject(branchSchema as Schema, branchNames[i], ctx, `${path}[${i}]`);
  });
  return unionName;
}

/**
 * Emit object members for a named interface. For each `properties[k]`: required
 * (in `required`, or when `required` is absent → all members required) →
 * `k: <type>`, otherwise `k?: <type>`. Property names are emitted as-is when
 * valid TS identifiers, else JSON-quoted (JSON Schema allows any string key).
 * Nested object values / array-of-object elements become named support types
 * `<parentTypeName><Pascal(prop)>`.
 */
function emitObjectMembers(
  schema: Schema,
  parentName: string,
  ctx: EmitContext,
  path: string
): string[] {
  const properties = schema['properties'];
  const props: Record<string, Schema> =
    typeof properties === 'object' && properties !== null
      ? (properties as Record<string, Schema>)
      : {};
  const required = schema['required'];
  // `required` absent → all members required (JSON-Schema default is optional;
  // TS-derived schemas always carry `required`, so this matches the source).
  const requiredSet = Array.isArray(required)
    ? new Set(required as string[])
    : null;

  const lines: string[] = [];
  for (const [key, propSchema] of Object.entries(props)) {
    const memberName = isIdentifier(key) ? key : JSON.stringify(key);
    const optional = requiredSet !== null && !requiredSet.has(key) ? '?' : '';
    const memberType = emitTypeExpr(
      propSchema,
      {
        name: `${parentName}${sanitizeIdentifier(
          toPascal({ raw: key, words: tokenize(key) })
        )}`,
        path: `${path}/${key}`,
      },
      ctx
    );
    lines.push(`  ${memberName}${optional}: ${memberType};`);
  }
  return lines;
}

// ---------------------------------------------------------------------------
// $ref / definitions
// ---------------------------------------------------------------------------

/** Hoist `definitions`/`$defs` from a schema tree (merged, later-wins). */
function hoistDefs(ctx: EmitContext, node: unknown): void {
  if (node === null || typeof node !== 'object') return;
  if (Array.isArray(node)) {
    for (const v of node) hoistDefs(ctx, v);
    return;
  }
  const s = node as Schema;
  for (const dictKey of ['definitions', '$defs']) {
    const dict = s[dictKey];
    if (typeof dict === 'object' && dict !== null) {
      for (const [key, defSchema] of Object.entries(
        dict as Record<string, unknown>
      )) {
        // later-wins on name clash (input first, output second)
        ctx.defs.set(sanitizeIdentifier(key), defSchema as Schema);
      }
    }
  }
  for (const val of Object.values(s)) hoistDefs(ctx, val);
}

/**
 * Resolve a `$ref` against the hoisted defs and emit the target def as a named
 * type (interface/union/alias named by its sanitized key). Unresolvable refs
 * REJECT — never `unknown`.
 */
function emitRef(ref: string, path: string, ctx: EmitContext): string {
  const m = /^#\/(?:definitions|\$defs)\/(.+)$/.exec(ref);
  if (!m) throw reject(ctx, `unresolvable $ref: ${ref}`, path);
  const key = sanitizeIdentifier(m[1]);
  const def = ctx.defs.get(key);
  if (!def) throw reject(ctx, `unresolvable $ref: ${ref}`, path);
  return emitTypeExpr(def, { name: key, path: `${path}~${key}` }, ctx);
}

// ---------------------------------------------------------------------------
// Literals / enums
// ---------------------------------------------------------------------------

/** Emit `const` as a literal type; object/array consts REJECT. */
function emitConst(s: Schema, path: string, ctx: EmitContext): string {
  const v = s['const'];
  if (
    typeof v === 'string' ||
    typeof v === 'number' ||
    typeof v === 'boolean' ||
    v === null
  ) {
    return lit(v);
  }
  throw reject(ctx, 'const object value is not supported (round 1)', path);
}

/** Emit a literal enum as `'a' | 'b'`; the boolean pair collapses to `boolean`. */
function emitEnum(s: Schema, path: string, ctx: EmitContext): string {
  const values = s['enum'];
  if (!Array.isArray(values)) {
    throw reject(ctx, 'invalid enum construct', path);
  }
  for (const v of values) {
    if (typeof v !== 'string' && typeof v !== 'number' && typeof v !== 'boolean') {
      throw reject(ctx, 'non-literal enum value is not supported (round 1)', path);
    }
  }
  if (values.length === 0) return 'never';
  if (
    values.length === 2 &&
    values.every((v) => typeof v === 'boolean')
  ) {
    return 'boolean';
  }
  return values.map((v) => lit(v)).join(' | ');
}

/**
 * Render a literal as TS source. Strings use single quotes (matching SPEC
 * §6.1's examples — `'cat'`, `'admin' | 'user'`); numbers/booleans/null use
 * JSON spelling.
 */
function lit(v: string | number | boolean | null): string {
  if (typeof v === 'string') {
    return `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  }
  return JSON.stringify(v);
}

// ---------------------------------------------------------------------------
// Guards + errors
// ---------------------------------------------------------------------------

/**
 * Reject the round-1-unsupported constructs. Called at every schema node so a
 * nested occurrence anywhere in the tree fails with the property path.
 */
function checkRejections(s: Schema, path: string, ctx: EmitContext): void {
  const REJECTED_KEYS: Array<[string, string]> = [
    ['allOf', 'allOf is not supported (round 1)'],
    ['anyOf', 'anyOf is not supported (round 1)'],
    ['patternProperties', 'patternProperties is not supported (round 1)'],
    ['not', 'not is not supported (round 1)'],
    ['if', 'if is not supported (round 1)'],
    ['then', 'then is not supported (round 1)'],
    ['else', 'else is not supported (round 1)'],
    ['contains', 'contains is not supported (round 1)'],
    ['propertyNames', 'propertyNames is not supported (round 1)'],
    ['unevaluatedProperties', 'unevaluatedProperties is not supported (round 1)'],
  ];
  for (const [key, msg] of REJECTED_KEYS) {
    if (s[key] !== undefined) throw reject(ctx, msg, path);
  }
  if (
    s['oneOf'] !== undefined &&
    !isDiscriminated(s) &&
    indexOfNullBranch(s) < 0
  ) {
    throw reject(ctx, 'oneOf without discriminator is not supported (round 1)', path);
  }
  if (s['additionalProperties'] !== undefined && s['additionalProperties'] !== false) {
    throw reject(ctx, 'additionalProperties schema is not supported (round 1)', path);
  }
}

function isDiscriminated(s: Schema): boolean {
  const d = s['discriminator'];
  return (
    typeof d === 'object' &&
    d !== null &&
    !!(d as Record<string, unknown>)['propertyName']
  );
}

/** Index of a `{ "type": "null" }` branch inside a `oneOf` array, or -1. */
function indexOfNullBranch(s: Schema): number {
  const oneOf = s['oneOf'];
  if (!Array.isArray(oneOf)) return -1;
  return oneOf.findIndex(
    (b) => typeof b === 'object' && b !== null && (b as Schema)['type'] === 'null'
  );
}

function isObjectSchema(s: Schema): boolean {
  return s['type'] === 'object' || hasProperties(s);
}

function hasProperties(s: Schema): boolean {
  return typeof s['properties'] === 'object' && s['properties'] !== null;
}

/** A property name is emitted unquoted when it is a valid TS identifier. */
function isIdentifier(key: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
}

/** Build the standard rejection error: prefix + message + fn + property path. */
function reject(ctx: EmitContext, msg: string, path: string): Error {
  return new Error(
    `[apigen-plugin-ts-types] ${msg} (fn: ${ctx.fnName}, path: ${path})`
  );
}
