import type { PluginInput, PluginOutput } from '@adhd/apigen-core'
import { generateStdioServer } from './templates/server-stdio.tpl'
import { generateHttpServer } from './templates/server-http.tpl'

/** Generates the index.ts file that exports toolMetas, groupFns, groupCreateClient. */
function generateIndex(
  packages: PluginInput['packages'],
  descriptions: Record<string, string>,
): string {
  const lines: string[] = [
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
  ]
  for (const pkg of packages) {
    lines.push(`import * as ${pkg.id}_fns from '${pkg.importPath}'`)
  }
  lines.push(``)
  lines.push(
    `export const toolMetas: Record<string, { group: string; schema: unknown }> = {`,
  )
  for (const pkg of packages) {
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      const desc = descriptions[fnName] ?? fnName
      lines.push(
        `  ${fnName}: { group: '${pkg.id}', schema: ${JSON.stringify(fnSchema)} }, // ${desc}`,
      )
    }
  }
  lines.push(`}`)
  lines.push(``)
  lines.push(
    `export const groupFns: Record<string, Record<string, (...args: unknown[]) => unknown>> = {`,
  )
  for (const pkg of packages) {
    lines.push(
      `  '${pkg.id}': ${pkg.id}_fns as Record<string, (...args: unknown[]) => unknown>,`,
    )
  }
  lines.push(`}`)
  lines.push(``)
  lines.push(
    `export const groupCreateClient: Record<string, ((e: Record<string, unknown>) => Promise<unknown>) | undefined> = {`,
  )
  for (const pkg of packages) {
    lines.push(
      `  '${pkg.id}': undefined, // injected at startup if createClient provided`,
    )
  }
  lines.push(`}`)
  return lines.join('\n')
}

export function generate(input: PluginInput): PluginOutput {
  const transport = (input.options['transport'] as string) ?? 'stdio'
  const port = (input.options['port'] as number) ?? 3000
  const descriptions =
    (input.options['toolDescriptions'] as Record<string, string>) ?? {}

  const indexContent = generateIndex(input.packages, descriptions)
  const serverContent =
    transport === 'stdio'
      ? generateStdioServer()
      : generateHttpServer(transport as 'sse' | 'streaming-http', port)

  return {
    files: [
      { path: 'index.ts', content: indexContent },
      { path: 'server.ts', content: serverContent },
    ],
  }
}
