import type {
  Operation,
  PluginInput,
  PluginOutput,
} from '@adhd/apigen-core-client';
import { buildOpPlan, buildToolDescription } from '@adhd/apigen-engine-runtime';
import { generateStdioServer } from './templates/server-stdio.tpl';
import { generateHttpServer } from './templates/server-http.tpl';
import { operationFor } from './tool-naming';

/**
 * Generates the index.ts file that exports toolMetas, groupFns,
 * groupCreateClient.
 *
 * `operations` is the real merged `Operation[]` when available —
 * DEBT-APIGEN-PLUGIN-MCP-GENERATE-OPERATIONS-001 (RESOLVED): `PluginInput`
 * now carries an optional `operations?: Operation[]`
 * (`@adhd/apigen-core-client`), threaded through by
 * `entrypoint/apigen-cli`'s `orchestrateGenerate()`. When absent (e.g. a bare
 * `PluginInput` built directly by a test), tool names are derived
 * best-effort from `pkg.id`/`pkg.importPath`/`fnName` — see
 * `./tool-naming.ts`'s `operationFor` doc comment.
 */
function generateIndex(
  packages: PluginInput['packages'],
  descriptions: Record<string, string>,
  operations?: Operation[]
): string {
  const lines: string[] = [
    `// Auto-generated by @adhd/apigen-cli — do not edit`,
    `import { buildFnTable } from '@adhd/apigen-engine-runtime'`,
  ];
  for (const pkg of packages) {
    lines.push(`import * as ${pkg.id}_ns from '${pkg.importPath}'`);
    lines.push(
      `const ${pkg.id}_fns = buildFnTable(${pkg.id}_ns as Record<string, unknown>)`
    );
  }
  lines.push(``);
  // BUG-APIGEN-OPENAPI-ROUTE-PATH-MISMATCH-001: keyed by the CANONICAL MCP
  // tool name — [mcp-adapter.3] collapsed the old `deriveToolName` shim into
  // `buildOpPlan(...).mcp.name` (`@adhd/apigen-engine-runtime`), the SAME
  // primitive `run()` builds its OpPlan table from, so generate-time and
  // run-time tool names are guaranteed byte-identical for the same input.
  // `fnName` is carried on each entry so the generated server.ts dispatches
  // to the correct real function under the new name (see
  // templates/server-*.tpl.ts).
  lines.push(
    `export const toolMetas: Record<string, { group: string; fnName: string; schema: unknown; description: string }> = {`
  );
  for (const pkg of packages) {
    for (const [fnName, fnSchema] of Object.entries(pkg.schemas)) {
      const op = operationFor({ id: pkg.id, importPath: pkg.importPath }, fnName, operations);
      const plan = buildOpPlan({ op, schema: fnSchema, transport: 'mcp' });
      const toolName = plan.mcp.name;
      // BUG-APIGEN-020: bake the tool description (user override + the
      // auto-generated data-envelope calling-convention note carried on
      // `fnSchema.input.description`, see composeSchemas) in at GENERATE
      // time — deterministic, byte-identical output, zero runtime cost.
      // Look up the description override by the new canonical name first,
      // falling back to the OLD raw-fnName key for backward compat.
      const desc = buildToolDescription(
        toolName,
        fnSchema as { input?: { description?: unknown } },
        descriptions[toolName] ?? descriptions[fnName]
      );
      lines.push(
        `  ${JSON.stringify(toolName)}: { group: '${pkg.id}', fnName: ${JSON.stringify(
          fnName
        )}, schema: ${JSON.stringify(fnSchema)}, description: ${JSON.stringify(
          desc
        )} },`
      );
    }
  }
  lines.push(`}`);
  lines.push(``);
  lines.push(
    `export const groupFns: Record<string, Record<string, (...args: unknown[]) => unknown>> = {`
  );
  for (const pkg of packages) {
    lines.push(
      `  '${pkg.id}': ${pkg.id}_fns as Record<string, (...args: unknown[]) => unknown>,`
    );
  }
  lines.push(`}`);
  lines.push(``);
  lines.push(
    `export const groupCreateClient: Record<string, ((e: Record<string, unknown>) => Promise<unknown>) | undefined> = {`
  );
  for (const pkg of packages) {
    lines.push(
      `  '${pkg.id}': undefined, // injected at startup if createClient provided`
    );
  }
  lines.push(`}`);
  return lines.join('\n');
}

export function generate(input: PluginInput): PluginOutput {
  const transport = (input.options['transport'] as string) ?? 'stdio';
  const port = (input.options['port'] as number) ?? 3000;
  const descriptions =
    (input.options['toolDescriptions'] as Record<string, string>) ?? {};

  // DEBT-APIGEN-PLUGIN-MCP-GENERATE-OPERATIONS-001 (RESOLVED): `PluginInput`
  // now carries `operations?: Operation[]` directly, threaded through by
  // `entrypoint/apigen-cli`'s `orchestrateGenerate()` the same way
  // `orchestrateRun()` threads `RunInput.operations` (BUG-APIGEN-024).
  const operations = input.operations;

  const indexContent = generateIndex(input.packages, descriptions, operations);
  const serverContent =
    transport === 'stdio'
      ? generateStdioServer()
      : generateHttpServer(transport as 'sse' | 'streaming-http', port);

  return {
    files: [
      { path: 'index.ts', content: indexContent },
      { path: 'server.ts', content: serverContent },
    ],
  };
}
