export type AgentMcpErrorCode =
  | "AGENT_NOT_FOUND"
  | "AGENT_ALREADY_EXISTS"
  | "AGENT_HAS_ACTIVE_SESSIONS"
  | "SESSION_NOT_FOUND"
  | "SESSION_CLOSED"
  | "TASK_NOT_FOUND"
  | "TASK_NOT_CANCELLABLE"
  | "DELEGATION_NOT_ALLOWED"
  | "MAX_DEPTH_EXCEEDED"
  | "MAX_TOOL_LOOPS_EXCEEDED"
  | "PROVIDER_ERROR"
  | "MCP_CLIENT_ERROR"
  | "VALIDATION_ERROR";
