"""Assert the Python primitives reproduce every pinned cross-language vector.

Source of truth (AUTHORITATIVE):
    packages/environment/environment-base-spec/spec/cross-language-test-vectors.json

That file is GENERATED by ``generateCrossLanguageVectors()`` in the base-spec
``src/index.ts`` (the TypeScript reference implementation) -- it is never
hand-authored, so a pinned ``expected`` can never silently drift from the
implementation that produced it. This suite loads that file and asserts the
Python port reproduces every vector, including the adversarial cases
(astral-plane key ordering, dotted project names, secret-leaf metadata
stripping, injective serialization of ``\\n``/``=`` values, and the
lone-surrogate error case).

Per the file's ``description``: contentHash / projectEnvPrefix / inferEnvVar
are compared by exact string equality; generateFieldSchema is compared by
structural (deep) equality of the parsed JSON object -- plain Python
dict/list equality already implements that. A vector carrying ``error``
(instead of ``expected``) is a specified FAILURE case: the port must raise
the named error.

Never change an existing vector by hand -- regenerate the JSON from the
TypeScript generator (see base-spec SPEC.md section 8) and update all three
clients in the same change.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from adhd_environment import LoneSurrogateError
from adhd_environment.environment import (
    content_hash,
    generate_field_schema,
    infer_env_var,
    project_env_prefix,
)

#: packages/environment/environment-base-spec/spec/cross-language-test-vectors.json
#: (this file lives at packages/environment/environment-core-py/tests/, so the
#: base-spec sibling package is two directories up).
VECTORS_PATH = (
    Path(__file__).resolve().parents[2]
    / "environment-base-spec"
    / "spec"
    / "cross-language-test-vectors.json"
)


def _load_vectors() -> dict[str, Any]:
    if not VECTORS_PATH.is_file():
        return {
            "contentHash": [],
            "projectEnvPrefix": [],
            "inferEnvVar": [],
            "generateFieldSchema": [],
        }
    with VECTORS_PATH.open("r", encoding="utf-8") as handle:
        return json.load(handle)


_VECTORS = _load_vectors()


def _content_hash_input(vector: dict[str, Any]) -> dict[str, str]:
    """Reconstruct a contentHash vector's input, including error-case inputs
    encoded as UTF-16 code units (a lone surrogate cannot be a literal JSON
    string that every parser accepts -- see ``inputKeyCodeUnits``)."""
    if "inputKeyCodeUnits" in vector:
        key = "".join(chr(unit) for unit in vector["inputKeyCodeUnits"])
        return {key: vector["inputValue"]}
    return vector["input"]


def test_vectors_file_exists() -> None:
    """The pinned vectors file must exist -- everything else in this module
    is meaningless without it."""
    assert VECTORS_PATH.is_file(), f"pinned cross-language vectors file missing: {VECTORS_PATH}"


def test_vectors_file_is_nonempty() -> None:
    assert _VECTORS.get("contentHash"), "no contentHash vectors loaded"
    assert _VECTORS.get("projectEnvPrefix"), "no projectEnvPrefix vectors loaded"
    assert _VECTORS.get("inferEnvVar"), "no inferEnvVar vectors loaded"
    assert _VECTORS.get("generateFieldSchema"), "no generateFieldSchema vectors loaded"


def test_vectors_are_content_hash_format_v2() -> None:
    """Guards against replaying the pre-ENV-CORE-004 (non-injective) vectors."""
    assert _VECTORS.get("contentHashFormatVersion") == 2


@pytest.mark.parametrize(
    "vector", _VECTORS.get("contentHash", []), ids=lambda v: v["name"]
)
def test_content_hash_vector(vector: dict[str, Any]) -> None:
    input_map = _content_hash_input(vector)
    if "error" in vector:
        # Specified failure case (e.g. lone surrogate). The port MUST raise.
        with pytest.raises(LoneSurrogateError):
            content_hash(input_map)
    else:
        assert content_hash(input_map) == vector["expected"]


@pytest.mark.parametrize(
    "vector", _VECTORS.get("projectEnvPrefix", []), ids=lambda v: v["name"]
)
def test_project_env_prefix_vector(vector: dict[str, Any]) -> None:
    assert project_env_prefix(vector["input"]) == vector["expected"]


@pytest.mark.parametrize(
    "vector", _VECTORS.get("inferEnvVar", []), ids=lambda v: v["name"]
)
def test_infer_env_var_vector(vector: dict[str, Any]) -> None:
    result = infer_env_var(vector["input"]["prefix"], vector["input"]["fieldPath"])
    assert result == vector["expected"]


@pytest.mark.parametrize(
    "vector", _VECTORS.get("generateFieldSchema", []), ids=lambda v: v["name"]
)
def test_generate_field_schema_vector(vector: dict[str, Any]) -> None:
    # Structural equality per the vectors file's comparison semantics --
    # plain dict equality already ignores key insertion order.
    assert generate_field_schema(vector["input"]) == vector["expected"]


def test_content_hash_unsorted_and_presorted_inputs_agree() -> None:
    """Belt-and-braces on top of the parametrized vectors above: prove the
    two 'same content, different input key order' vectors produce the
    exact same hash as each other, not just the same hash as the pinned
    expected string."""
    unsorted = next(
        v for v in _VECTORS["contentHash"] if v["name"] == "spec-example-unsorted-input"
    )
    presorted = next(
        v for v in _VECTORS["contentHash"] if v["name"] == "spec-example-pre-sorted-input"
    )
    assert content_hash(unsorted["input"]) == content_hash(presorted["input"])


# ---------------------------------------------------------------------------
# Adversarial regression guards (ENV-CORE-002/004/005) -- these have TEETH:
# each fails if the corresponding fix is reverted.
# ---------------------------------------------------------------------------


def test_content_hash_astral_key_ordering_matches_reference() -> None:
    """ENV-CORE-002: a BMP key (U+FFFF) and an astral key (U+1F600) must hash
    to the reference (code-point-ordered) digest. A UTF-16 code-unit sort
    would order the astral key first and produce a different digest."""
    vector = next(
        v for v in _VECTORS["contentHash"] if v["name"] == "astral-plane-key-ordering"
    )
    assert content_hash(vector["input"]) == vector["expected"]


def test_content_hash_serialization_is_injective() -> None:
    """ENV-CORE-004: the old key=value\\n form collided
    ({a:'1\\nb=2'} == {a:'1',b:'2'}); the v2 length-prefixed form must not."""
    assert content_hash({"a": "1\nb=2"}) != content_hash({"a": "1", "b": "2"})


def test_content_hash_rejects_lone_surrogate() -> None:
    """ENV-CORE-005: a lone surrogate in a key or value must raise
    LoneSurrogateError, not silently substitute U+FFFD or raise a raw
    UnicodeEncodeError."""
    lone = chr(0xD800)
    with pytest.raises(LoneSurrogateError):
        content_hash({lone: "x"})
    with pytest.raises(LoneSurrogateError):
        content_hash({"k": lone})
