import { db, sqlite } from "./client.js";
import { runMigrationsOn } from "./migrate-runner.js";

/**
 * Runs pending Drizzle migrations synchronously before the server starts.
 * Migrations are read from the ./drizzle folder (generated by drizzle-kit).
 *
 * Delegates to the FK-safe {@link runMigrationsOn} runner (see that module for
 * why foreign-key enforcement must be toggled around the migration run).
 */
export function runMigrations(): void {
    runMigrationsOn(sqlite, db);
}
