name: Setup Sentry-Cli
description: GitHub Action to Install Sentry
branding:
  color: blue
  icon: command
inputs:
  version:
    description: ""
    required: true
runs:
  using: composite
  steps:
  - name: "Install Sentry-Cli"
    shell: bash
    run: |
      export INSTALL_DIR="${{ runner.tool_cache }}/sentry-cli"
      mkdir -v -p "$INSTALL_DIR"

      if [ -f "$INSTALL_DIR/sentry-cli" ]; then
        echo "sentry-cli is already installed in cache"
      else
        curl -sL https://sentry.io/get-cli/ | bash
      fi

      echo "Adding $INSTALL_DIR to PATH"
      echo "$INSTALL_DIR" >> $GITHUB_PATH
  - name: "Verify Installation of Sentry-Cli"
    shell: bash
    run: |
      echo "Sentry Version: $(sentry-cli -V)"
      echo "$PATH"
