name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    env:
      GH_MERGED: ${{github.event.pull_request.merged}}
      GH_ACTION: ${{github.event.action}}
      GH_HEAD_REF: ${{ github.event.pull_request.head.ref }}
      GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      GH_BASE_REF: ${{ github.event.pull_request.base.ref }}
      GH_BASE_SHA: ${{ github.event.pull_request.base.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Install dependencies
        run: |
          yarn # --frozen-lockfile
          echo ""
          echo "GH_MERGED: $GH_MERGED"
          echo "GH_ACTION: $GH_ACTION"
          echo "GH_BASE_REF: $GH_BASE_REF"
          echo "GH_HEAD_REF: $GH_HEAD_REF"
          echo "GH_BASE_SHA: $GH_BASE_SHA"
          echo "GH_HEAD_SHA: $GH_HEAD_SHA"

      # - uses: actions/cache@v3
      #   id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      #   with:
      #     path: |
      #       ${{ github.workspace }}/node_modules
      #       !${{ github.workspace }}/node_modules/.cache
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      # - name: Install dependencies
      #   if: steps.yarn-cache.outputs.cache-hit != 'true'

      - uses: nrwl/nx-set-shas@v4
      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}

      - run: npx nx format:check
      - run: npx nx affected -t lint test build
