# File for Pull Request on main branch
name: PR

on:
  pull_request:
    types: [labeled, closed, opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NX_NO_CLOUD: true
      GH_MERGED: ${{ github.event.pull_request.merged }}
      GH_ACTION: ${{ github.event.action }}
      GH_PR_COMPLETE: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
      GH_HEAD_REF: ${{ github.event.pull_request.head.ref }}
      GH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      GH_BASE_REF: ${{ github.event.pull_request.base.ref }}
      GH_BASE_SHA: ${{ github.event.pull_request.base.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Derive SHAs for nx affected
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: main

      - name: Install dependencies
        run: yarn

      - name: Lint
        id: lint
        run: npx nx affected -t lint --parallel=5

      - name: Test
        id: test
        run: npx nx affected -t test --parallel=5

      - name: Publish
        id: publish
        if: success() && (contains(github.event.pull_request.labels.*.name, 'publish') || (github.event.action == 'closed' && github.event.pull_request.merged == true))
        run: |
          EXCLUDE=$(npx nx show projects --type=app | tr -s '[:blank:]' ',')
          AFFECTED=$(npx nx show projects --affected --exclude=$EXCLUDE | tr -s '[:blank:]' ',')
          if [ -z "$AFFECTED" ]; then
            echo "No libraries impacted"
            echo "affected=NA" >> $GITHUB_OUTPUT
          else
            npx nx affected -t build --exclude=$EXCLUDE --parallel=4
            npx nx affected -t version --exclude=$EXCLUDE --parallel=4
            npx nx affected -t publish --exclude=$EXCLUDE --configuration=production --parallel=4
            echo "affected=$AFFECTED" >> $GITHUB_OUTPUT
          fi

      - name: Find Publish Comment
        uses: peter-evans/find-comment@v2
        if: github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'publish') || (github.event.action == 'closed' && github.event.pull_request.merged == true))
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: preview-publish

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        if: github.event_name == 'pull_request' && (contains(github.event.pull_request.labels.*.name, 'publish') || (github.event.action == 'closed' && github.event.pull_request.merged == true))
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Packages [preview-publish]
            ### Affected
            ${{ steps.publish.outputs.affected }}
          edit-mode: replace
